/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/room/retro_room.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, OrthographicCamera } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh;
    Plane_1: THREE.Mesh;
    Plane_2: THREE.Mesh;
    Cube: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube003_1: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube005: THREE.Mesh;
    Shelf: THREE.Mesh;
    Cylinder: THREE.Mesh;
    Circle005: THREE.Mesh;
    Circle006: THREE.Mesh;
    Fan: THREE.Mesh;
    Cube006: THREE.Mesh;
    Cylinder003: THREE.Mesh;
    Circle040: THREE.Mesh;
    Cylinder005: THREE.Mesh;
    Cylinder006: THREE.Mesh;
    Cylinder007: THREE.Mesh;
    Plane012: THREE.Mesh;
    Plane012_1: THREE.Mesh;
    DND: THREE.Mesh;
    Calendar: THREE.Mesh;
    calendar: THREE.Mesh;
    Circle045: THREE.Mesh;
    Poster001: THREE.Mesh;
    Poster: THREE.Mesh;
    Chocofur_Books_13_1: THREE.Mesh;
    Chocofur_Books_13_1_1: THREE.Mesh;
    Chocofur_Books_13_1_2: THREE.Mesh;
    Chocofur_Books_13_1_3: THREE.Mesh;
    Chocofur_Books_13_1_4: THREE.Mesh;
    Chocofur_Books_13_1_5: THREE.Mesh;
    Chocofur_Books_13_1_6: THREE.Mesh;
    Chocofur_Books_13_1_7: THREE.Mesh;
    Chocofur_Books_13_1_8: THREE.Mesh;
    Chocofur_Books_13_1_9: THREE.Mesh;
    Chocofur_Books_13_1_10: THREE.Mesh;
    Chocofur_Books_13_1_11: THREE.Mesh;
    Chocofur_Books_13_1_12: THREE.Mesh;
    Chocofur_Books_13_1_13: THREE.Mesh;
    Chocofur_Books_13_1_14: THREE.Mesh;
    Chocofur_Books_13_1_15: THREE.Mesh;
    Chocofur_Books_13_1_16: THREE.Mesh;
    Chocofur_Books_13_1_17: THREE.Mesh;
    Chocofur_Books_13_1_18: THREE.Mesh;
    Plane091: THREE.Mesh;
    Plane092: THREE.Mesh;
    Plane093: THREE.Mesh;
    Plane094: THREE.Mesh;
    Plane095: THREE.Mesh;
    Plane096: THREE.Mesh;
    Plane097: THREE.Mesh;
    Plane098: THREE.Mesh;
    Plane099: THREE.Mesh;
    Plane100: THREE.Mesh;
    Plane101: THREE.Mesh;
    Plane102: THREE.Mesh;
    Plane103: THREE.Mesh;
    Plane104: THREE.Mesh;
    Plane105: THREE.Mesh;
    Plane106: THREE.Mesh;
    Plane107: THREE.Mesh;
    Plane108: THREE.Mesh;
    Plane109: THREE.Mesh;
    Plane110: THREE.Mesh;
    Plane111: THREE.Mesh;
    Plane112: THREE.Mesh;
    Plane113: THREE.Mesh;
    Plane114: THREE.Mesh;
    Plane116: THREE.Mesh;
    Plane117: THREE.Mesh;
    Plane118: THREE.Mesh;
    Plane119: THREE.Mesh;
    Plane120: THREE.Mesh;
    Plane121: THREE.Mesh;
    Plane122: THREE.Mesh;
    Plane123: THREE.Mesh;
    Plane124: THREE.Mesh;
    Plane125: THREE.Mesh;
    Plane126: THREE.Mesh;
    Plane127: THREE.Mesh;
    Plane128: THREE.Mesh;
    Plane129: THREE.Mesh;
    Plane130: THREE.Mesh;
    Plane131: THREE.Mesh;
    Plane132: THREE.Mesh;
    Plane133: THREE.Mesh;
    Plane134: THREE.Mesh;
    Plane135: THREE.Mesh;
    Plane136: THREE.Mesh;
    Plane137: THREE.Mesh;
    Plane138: THREE.Mesh;
    Plane151: THREE.Mesh;
    Plane152: THREE.Mesh;
    Plane153: THREE.Mesh;
    Plane154: THREE.Mesh;
    Plane155: THREE.Mesh;
    Plane156: THREE.Mesh;
    Plane157: THREE.Mesh;
    Plane158: THREE.Mesh;
    Plane159: THREE.Mesh;
    Plane160: THREE.Mesh;
    Plane115: THREE.Mesh;
    Plane139: THREE.Mesh;
    Plane140: THREE.Mesh;
    Plane141: THREE.Mesh;
    Plane142: THREE.Mesh;
    Plane143: THREE.Mesh;
    Plane144: THREE.Mesh;
    Plane145: THREE.Mesh;
    Plane146: THREE.Mesh;
    Plane147: THREE.Mesh;
    Plane148: THREE.Mesh;
    Plane149: THREE.Mesh;
    Plane150: THREE.Mesh;
    Plane161: THREE.Mesh;
  };
  materials: {
    Wall: THREE.MeshStandardMaterial;
    Floor: THREE.MeshStandardMaterial;
    ["Wall.001"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    Wood2: THREE.MeshStandardMaterial;
    Light: THREE.MeshStandardMaterial;
    White: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["Paint.005"]: THREE.MeshStandardMaterial;
    ["Paint.007"]: THREE.MeshStandardMaterial;
    Metal: THREE.MeshStandardMaterial;
    ["White.001"]: THREE.MeshStandardMaterial;
    Book: THREE.MeshStandardMaterial;
    dnd: THREE.MeshStandardMaterial;
    calendar: THREE.MeshStandardMaterial;
    ["Metal.001"]: THREE.MeshStandardMaterial;
    ["poster-future"]: THREE.MeshStandardMaterial;
    ["poster-vanhalen"]: THREE.MeshStandardMaterial;
    ["Chocofur_Books_13.001"]: THREE.MeshStandardMaterial;
    ["Chocofur_Books_13.002"]: THREE.MeshStandardMaterial;
    ["Chocofur_Books_13.018"]: THREE.MeshStandardMaterial;
    ["Chocofur_Books_13.010"]: THREE.MeshStandardMaterial;
    Chocofur_Books_13: THREE.MeshStandardMaterial;
    ["Chocofur_Books_13.011"]: THREE.MeshStandardMaterial;
    ["Chocofur_Books_13.009"]: THREE.MeshStandardMaterial;
    ["Chocofur_Books_13.008"]: THREE.MeshStandardMaterial;
    ["Chocofur_Books_13.007"]: THREE.MeshStandardMaterial;
    ["Chocofur_Books_13.006"]: THREE.MeshStandardMaterial;
    ["Chocofur_Books_13.005"]: THREE.MeshStandardMaterial;
    ["Chocofur_Books_13.004"]: THREE.MeshStandardMaterial;
    ["Chocofur_Books_13.003"]: THREE.MeshStandardMaterial;
    ["Chocofur_Books_13.017"]: THREE.MeshStandardMaterial;
    ["Chocofur_Books_13.016"]: THREE.MeshStandardMaterial;
    ["Chocofur_Books_13.015"]: THREE.MeshStandardMaterial;
    ["Chocofur_Books_13.013"]: THREE.MeshStandardMaterial;
    ["Chocofur_Books_13.014"]: THREE.MeshStandardMaterial;
    ["Chocofur_Books_13.012"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
  };
};

export function Room1(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/room/room1.glb") as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, -2.5, 0]}>
      <OrthographicCamera
        makeDefault={true}
        far={1000}
        near={0.1}
        position={[30.61, 33.06, 30.61]}
        rotation={[-0.79, 0.62, 0.52]}
        zoom={62}
      />
      <mesh
        geometry={nodes.Shelf.geometry}
        material={materials.Wood2}
        position={[-4, 3.82, 1.81]}
      />
      <mesh
        geometry={nodes.Fan.geometry}
        material={materials["Paint.007"]}
        position={[-3.61, 4.01, 0.52]}
        rotation={[0, 0.22, 0]}
        scale={1.26}
      ></mesh>
      <group
        position={[-3.56, 4.05, 1.6]}
        rotation={[Math.PI / 2, 0, -0.27]}
        scale={[0.87, 0.87, 0.43]}
      >
        <mesh
          geometry={nodes.Plane012.geometry}
          material={materials["White.001"]}
        />
        <mesh geometry={nodes.Plane012_1.geometry} material={materials.Book} />
      </group>
      <mesh
        geometry={nodes.DND.geometry}
        material={materials.dnd}
        position={[-3.37, 4.1, 1.67]}
        rotation={[0, 0.61, 0]}
        scale={1.22}
      />
      <mesh
        geometry={nodes.Calendar.geometry}
        material={materials["White.001"]}
        position={[-4, 4.06, -2.53]}
      >
        <mesh
          geometry={nodes.calendar.geometry}
          material={materials.calendar}
          position={[0.06, 0.11, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.98, 0.98, 0.87]}
        />
        <mesh
          geometry={nodes.Circle045.geometry}
          material={materials["Metal.001"]}
          position={[0.04, 0.57, 0.59]}
          scale={0.64}
        />
      </mesh>
      <mesh
        geometry={nodes.Poster001.geometry}
        material={materials["poster-future"]}
        position={[2.03, 3.58, -3.99]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={2.5}
      />
      <mesh
        geometry={nodes.Poster.geometry}
        material={materials["poster-vanhalen"]}
        position={[3.35, 3.4, -3.99]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.47}
      />
      <group
        position={[-3.58, 4.33, 3.33]}
        rotation={[-0.05, Math.PI / 2, 0]}
        scale={1.28}
      >
        <mesh
          geometry={nodes.Chocofur_Books_13_1.geometry}
          material={materials["Chocofur_Books_13.001"]}
        />
        <mesh
          geometry={nodes.Chocofur_Books_13_1_1.geometry}
          material={materials["Chocofur_Books_13.002"]}
        />
        <mesh
          geometry={nodes.Chocofur_Books_13_1_2.geometry}
          material={materials["Chocofur_Books_13.018"]}
        />
        <mesh
          geometry={nodes.Chocofur_Books_13_1_3.geometry}
          material={materials["Chocofur_Books_13.010"]}
        />
        <mesh
          geometry={nodes.Chocofur_Books_13_1_4.geometry}
          material={materials.Chocofur_Books_13}
        />
        <mesh
          geometry={nodes.Chocofur_Books_13_1_5.geometry}
          material={materials["Chocofur_Books_13.011"]}
        />
        <mesh
          geometry={nodes.Chocofur_Books_13_1_6.geometry}
          material={materials["Chocofur_Books_13.009"]}
        />
        <mesh
          geometry={nodes.Chocofur_Books_13_1_7.geometry}
          material={materials["Chocofur_Books_13.008"]}
        />
        <mesh
          geometry={nodes.Chocofur_Books_13_1_8.geometry}
          material={materials["Chocofur_Books_13.007"]}
        />
        <mesh
          geometry={nodes.Chocofur_Books_13_1_9.geometry}
          material={materials["Chocofur_Books_13.006"]}
        />
        <mesh
          geometry={nodes.Chocofur_Books_13_1_10.geometry}
          material={materials["Chocofur_Books_13.005"]}
        />
        <mesh
          geometry={nodes.Chocofur_Books_13_1_11.geometry}
          material={materials["Chocofur_Books_13.004"]}
        />
        <mesh
          geometry={nodes.Chocofur_Books_13_1_12.geometry}
          material={materials["Chocofur_Books_13.003"]}
        />
        <mesh
          geometry={nodes.Chocofur_Books_13_1_13.geometry}
          material={materials["Chocofur_Books_13.017"]}
        />
        <mesh
          geometry={nodes.Chocofur_Books_13_1_14.geometry}
          material={materials["Chocofur_Books_13.016"]}
        />
        <mesh
          geometry={nodes.Chocofur_Books_13_1_15.geometry}
          material={materials["Chocofur_Books_13.015"]}
        />
        <mesh
          geometry={nodes.Chocofur_Books_13_1_16.geometry}
          material={materials["Chocofur_Books_13.013"]}
        />
        <mesh
          geometry={nodes.Chocofur_Books_13_1_17.geometry}
          material={materials["Chocofur_Books_13.014"]}
        />
        <mesh
          geometry={nodes.Chocofur_Books_13_1_18.geometry}
          material={materials["Chocofur_Books_13.012"]}
        />
      </group>
      <mesh geometry={nodes.Plane.geometry} material={materials.Wall} />
      <mesh geometry={nodes.Plane_1.geometry} material={materials.Floor} />
      <mesh
        geometry={nodes.Plane_2.geometry}
        material={materials["Wall.001"]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials.Wood2}
        position={[-1.43, 3.31, -4]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials.Wood2}
        position={[-1.43, 3.31, -4]}
      />
      <mesh
        geometry={nodes.Cube003_1.geometry}
        material={materials.Light}
        position={[-1.43, 3.31, -3.99]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials.Wood2}
        position={[-1.43, 3.31, -4]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials.White}
        position={[-1.43, 3.31, -3.95]}
      />
    </group>
  );
}
