/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/room/room4.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, OrthographicCamera } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane080: THREE.Mesh;
    Circle017: THREE.Mesh;
    Circle018: THREE.Mesh;
    Plane001: THREE.Mesh;
    Plane001_1: THREE.Mesh;
    Plane006: THREE.Mesh;
    Plane007: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane052: THREE.Mesh;
    Plane054: THREE.Mesh;
    Plane055: THREE.Mesh;
    Plane056: THREE.Mesh;
    Vert: THREE.Mesh;
    Plane058: THREE.Mesh;
    Circle006: THREE.Mesh;
    Cylinder: THREE.Mesh;
    Plane057: THREE.Mesh;
    Vert001: THREE.Mesh;
    Circle008: THREE.Mesh;
    Cylinder001: THREE.Mesh;
    Roundcube: THREE.Mesh;
    Vert004: THREE.Mesh;
    Circle007: THREE.Mesh;
    Circle007_1: THREE.Mesh;
    Vert002: THREE.Mesh;
    Vert003: THREE.Mesh;
    Circle007_2: THREE.Mesh;
    Circle007_3: THREE.Mesh;
    Circle007_4: THREE.Mesh;
    Circle007_5: THREE.Mesh;
    Plane060: THREE.Mesh;
    Plane027: THREE.Mesh;
    Plane005: THREE.Mesh;
    Sphere001_1: THREE.Mesh;
    Sphere002_1: THREE.Mesh;
    Vert006_1: THREE.Mesh;
    Vert007_1: THREE.Mesh;
    Circle014_1: THREE.Mesh;
    Roundcube001_1: THREE.Mesh;
    Vert008: THREE.Mesh;
    Vert009: THREE.Mesh;
    Circle015: THREE.Mesh;
    Roundcube002: THREE.Mesh;
    Sphere003: THREE.Mesh;
    Sphere004: THREE.Mesh;
  };
  materials: {
    Gold: THREE.MeshStandardMaterial;
    ["Glass.002"]: THREE.MeshPhysicalMaterial;
    Room: THREE.MeshStandardMaterial;
    ["Stone Wall"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    Wood2: THREE.MeshStandardMaterial;
    Light: THREE.MeshStandardMaterial;
    Grey: THREE.MeshStandardMaterial;
    Fabric: THREE.MeshStandardMaterial;
    Hallows: THREE.MeshPhysicalMaterial;
    ["Metal.001"]: THREE.MeshStandardMaterial;
    Black: THREE.MeshStandardMaterial;
    Glass: THREE.MeshPhysicalMaterial;
    Floor: THREE.MeshStandardMaterial;
    ["Glass.001"]: THREE.MeshPhysicalMaterial;
  };
};

export function Room4(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/room/room4.glb") as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, -2.5, 0]}>
      <OrthographicCamera
        makeDefault={true}
        far={1000}
        near={0.1}
        position={[30.61, 33.06, 30.61]}
        rotation={[-0.79, 0.62, 0.52]}
        zoom={62}
      />
      <mesh
        geometry={nodes.Plane080.geometry}
        material={materials.Gold}
        position={[-3.95, 1.52, 0.63]}
        rotation={[0, -0.62, 0]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Circle017.geometry}
        material={materials.Gold}
        position={[-3.99, 1.21, 0.6]}
      />
      <mesh
        geometry={nodes.Circle018.geometry}
        material={materials["Glass.002"]}
        position={[-3.99, 1.21, 0.6]}
      />
      <mesh
        // geometry={nodes.Plane006.geometry}
        material={materials["default"]}
        position={[-4, 0.94, 1.32]}
      />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={materials["default"]}
        position={[-4, 0.94, 1.32]}
      />
      <mesh
        geometry={nodes.Plane011.geometry}
        material={materials.Wood2}
        position={[-4, 0.94, 1.32]}
      />
      <mesh
        geometry={nodes.Plane052.geometry}
        material={materials.Light}
        position={[-3.99, 0.94, 1.32]}
      />
      <mesh
        geometry={nodes.Plane054.geometry}
        material={materials.Wood2}
        position={[-4, 0.94, 1.32]}
      />
      <mesh
        geometry={nodes.Plane055.geometry}
        material={materials.Grey}
        position={[-4, 0.94, 1.32]}
      />
      <mesh
        geometry={nodes.Plane056.geometry}
        material={materials.Fabric}
        position={[0.85, 5.86, -3.81]}
        scale={[0.56, 1, 1]}
      />
      <mesh
        geometry={nodes.Vert.geometry}
        material={materials.Wood2}
        position={[4, 6, -4]}
      />
      <mesh
        geometry={nodes.Plane058.geometry}
        material={materials.Hallows}
        position={[2.61, 4.57, -3.79]}
      >
        <mesh
          geometry={nodes.Circle006.geometry}
          material={materials.Gold}
          position={[0.69, 0, 0]}
        />
        <mesh
          geometry={nodes.Cylinder.geometry}
          material={materials["Metal.001"]}
        />
        <mesh
          geometry={nodes.Plane057.geometry}
          material={materials.Black}
          position={[0, 1.19, 0]}
        />
      </mesh>
      <mesh
        geometry={nodes.Vert001.geometry}
        material={materials.Wood2}
        position={[-4, 6, -1.03]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Circle008.geometry}
        material={materials.Gold}
        position={[-3.86, 1.21, 2.17]}
        rotation={[0, 0.29, 0]}
        scale={1.45}
      >
        <mesh
          // geometry={nodes.Cylinder001.geometry}
          material={materials.Gold}
          position={[0, 0.49, 0]}
          rotation={[0, -0.79, 0]}
          scale={1.05}
        >
          <mesh
            geometry={nodes.Roundcube.geometry}
            material={materials.Gold}
            position={[0, 0, -0.29]}
            rotation={[-0.16, 0, 0]}
          >
            <mesh geometry={nodes.Vert004.geometry} material={materials.Gold}>
              <group position={[0, 0.27, 0]}>
                <mesh
                  geometry={nodes.Circle007.geometry}
                  material={materials.Gold}
                />
                <mesh
                  geometry={nodes.Circle007_1.geometry}
                  material={materials.Glass}
                />
              </group>
            </mesh>
          </mesh>
          <mesh
            geometry={nodes.Vert002.geometry}
            material={materials.Gold}
            position={[0, 0.04, 0.16]}
            rotation={[0, -0.82, 0]}
          >
            <mesh
              geometry={nodes.Vert003.geometry}
              material={materials.Gold}
              position={[0, 0.21, 0]}
            >
              <group
                position={[0, 0, 0.15]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.52}
              >
                <mesh
                  geometry={nodes.Circle007_2.geometry}
                  material={materials.Gold}
                />
                <mesh
                  geometry={nodes.Circle007_3.geometry}
                  material={materials.Glass}
                />
              </group>
              <group
                position={[0, 0, -0.11]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.83}
              >
                <mesh
                  geometry={nodes.Circle007_4.geometry}
                  material={materials.Gold}
                />
                <mesh
                  geometry={nodes.Circle007_5.geometry}
                  material={materials.Glass}
                />
              </group>
            </mesh>
          </mesh>
        </mesh>
      </mesh>
      <mesh geometry={nodes.Plane060.geometry} material={materials.Floor} />
      <mesh
        geometry={nodes.Plane027.geometry}
        material={materials["Stone Wall"]}
        position={[-4, 0.94, 1.32]}
      />
      <mesh
        geometry={nodes.Plane005.geometry}
        material={materials.Gold}
        position={[-4, 5.19, 3.54]}
        scale={1.24}
      >
        <mesh
          geometry={nodes.Sphere001_1.geometry}
          material={materials.Gold}
          position={[0.71, 0.35, 0]}
          scale={1.18}
        />
        <mesh
          geometry={nodes.Sphere002_1.geometry}
          material={materials.Gold}
          position={[0.71, 0.35, 0]}
          scale={1.18}
        />
        <mesh
          geometry={nodes.Vert006_1.geometry}
          material={materials.Gold}
          position={[0.09, -0.03, 0]}
        />
        <mesh
          geometry={nodes.Vert007_1.geometry}
          material={materials.Gold}
          position={[0.09, -0.03, 0]}
        />
        <mesh
          geometry={nodes.Circle014_1.geometry}
          material={materials.Gold}
          position={[0.71, -0.03, 0]}
        />
        <mesh
          geometry={nodes.Roundcube001_1.geometry}
          material={materials["Glass.001"]}
          position={[0.71, 0.35, 0]}
          scale={1.18}
        />
      </mesh>
      <mesh
        geometry={nodes.Vert008.geometry}
        material={materials.Gold}
        position={[-3.91, 5.02, 3.54]}
      />
      <mesh
        geometry={nodes.Vert009.geometry}
        material={materials.Gold}
        position={[-3.91, 5.02, 3.54]}
      />
      <mesh
        geometry={nodes.Circle015.geometry}
        material={materials.Gold}
        position={[-3.29, 5.02, 3.54]}
      />
      <mesh
        geometry={nodes.Roundcube002.geometry}
        material={materials["Glass.001"]}
        position={[-3.29, 5.37, 3.54]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={materials.Gold}
        position={[-3.29, 5.37, 3.54]}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={materials.Gold}
        position={[-3.29, 5.37, 3.54]}
      />
      <mesh geometry={nodes.Plane001.geometry} material={materials.Room} />
      <mesh
        geometry={nodes.Plane001_1.geometry}
        material={materials["Stone Wall"]}
      />
    </group>
  );
}

// useGLTF.preload("/models/room/room4.glb");
