/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/room/room3.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { OrthographicCamera, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh;
    Plane_1: THREE.Mesh;
    Plane_2: THREE.Mesh;
    Window: THREE.Mesh;
    Plane021: THREE.Mesh;
    Plane022: THREE.Mesh;
    Plane023: THREE.Mesh;
    Plane031: THREE.Mesh;
    Plane034: THREE.Mesh;
    Plane035: THREE.Mesh;
    Door: THREE.Mesh;
    Plane017: THREE.Mesh;
    Plane024: THREE.Mesh;
    Plane046: THREE.Mesh;
    Plane036: THREE.Mesh;
    Plane036_1: THREE.Mesh;
    Light: THREE.Mesh;
    Socket: THREE.Mesh;
    Circle010: THREE.Mesh;
  };
  materials: {
    Wall: THREE.MeshStandardMaterial;
    Floor: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    Wood: THREE.MeshStandardMaterial;
    Window: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    Cloth: THREE.MeshPhysicalMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["Milk Glass"]: THREE.MeshPhysicalMaterial;
    Metal: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    Poster: THREE.MeshStandardMaterial;
    black: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
  };
};

export function Room3(props: JSX.IntrinsicElements["group"] | any) {
  const { nodes, materials } = useGLTF("/models/room/room3.glb") as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, -2.5, 0]}>
      <OrthographicCamera
        makeDefault={true}
        far={1000}
        near={0.1}
        position={[30.61, 33.06, 30.61]}
        rotation={[-0.79, 0.62, 0.52]}
        zoom={62}
      />
      <mesh material={materials["default"]}>
        <mesh geometry={nodes.Plane021.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Plane022.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Plane023.geometry} material={materials.Window} />
        <mesh
          geometry={nodes.Plane031.geometry}
          material={materials["default"]}
          position={[-3.96, 4.33, 1.14]}
        />
        <mesh
          geometry={nodes.Plane034.geometry}
          material={materials.Cloth}
          position={[-3.87, 4.21, 3.16]}
        />
        <mesh
          geometry={nodes.Plane035.geometry}
          material={materials.Cloth}
          position={[-3.87, 4.21, -0.81]}
        />
      </mesh>
      <mesh material={materials["default"]}>
        <mesh geometry={nodes.Plane017.geometry} material={materials.Wood} />
        <mesh
          geometry={nodes.Plane024.geometry}
          material={materials["Milk Glass"]}
        />
        <mesh
          geometry={nodes.Plane046.geometry}
          material={materials.Metal}
          position={[-4.12, 1.78, -1.92]}
        />
      </mesh>
      <group position={[2.24, 3.1, -3.99]}>
        <mesh
          geometry={nodes.Plane036.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Plane036_1.geometry}
          material={materials.Poster}
        />
      </group>
      <mesh
        geometry={nodes.Light.geometry}
        material={materials.Metal}
        position={[2.24, 4.48, -4]}
      ></mesh>
      <mesh
        geometry={nodes.Socket.geometry}
        material={materials.black}
        position={[3.61, 0.59, -4]}
      >
        <mesh
          geometry={nodes.Circle010.geometry}
          material={materials["default"]}
        />
      </mesh>
      <mesh geometry={nodes.Plane.geometry} material={materials.Wall} />
      <mesh
        userData={{ ground: true }}
        geometry={nodes.Plane_1.geometry}
        material={materials.Floor}
      />
      <mesh geometry={nodes.Plane_2.geometry} material={materials.Floor} />
    </group>
  );
}

// useGLTF.preload("/models/room/room3.glb");
