/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/room/room15.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, OrthographicCamera } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    low_poly_interior465: THREE.Mesh;
    low_poly_interior466: THREE.Mesh;
    low_poly_interior467: THREE.Mesh;
    low_poly_interior7981: THREE.Mesh;
    low_poly_interior7983: THREE.Mesh;
    low_poly_interior7984: THREE.Mesh;
    low_poly_interior7985: THREE.Mesh;
    low_poly_interior7986: THREE.Mesh;
    low_poly_interior7987: THREE.Mesh;
    low_poly_interior7988: THREE.Mesh;
    low_poly_interior7989: THREE.Mesh;
    low_poly_interior7990: THREE.Mesh;
    low_poly_interior7993: THREE.Mesh;
    low_poly_interior7994: THREE.Mesh;
    low_poly_interior7995: THREE.Mesh;
    low_poly_interior7996: THREE.Mesh;
    low_poly_interior7997: THREE.Mesh;
    low_poly_interior7998: THREE.Mesh;
    low_poly_interior7999: THREE.Mesh;
    low_poly_interior8000: THREE.Mesh;
    low_poly_interior8001: THREE.Mesh;
    low_poly_interior8002: THREE.Mesh;
    low_poly_interior8003: THREE.Mesh;
    low_poly_interior8004: THREE.Mesh;
    low_poly_interior8005: THREE.Mesh;
    low_poly_interior8006: THREE.Mesh;
    low_poly_interior8007: THREE.Mesh;
    low_poly_interior8008: THREE.Mesh;
    low_poly_interior8009: THREE.Mesh;
    low_poly_interior8010: THREE.Mesh;
    low_poly_interior8011: THREE.Mesh;
    low_poly_interior8012: THREE.Mesh;
    low_poly_interior8013: THREE.Mesh;
    low_poly_interior8014: THREE.Mesh;
    low_poly_interior8015: THREE.Mesh;
    low_poly_interior8016: THREE.Mesh;
    low_poly_interior8017: THREE.Mesh;
    low_poly_interior8018: THREE.Mesh;
    low_poly_interior8019: THREE.Mesh;
    low_poly_interior8020: THREE.Mesh;
    low_poly_interior8021: THREE.Mesh;
    low_poly_interior8022: THREE.Mesh;
    low_poly_interior8023: THREE.Mesh;
  };
  materials: {
    emit: THREE.MeshStandardMaterial;
    low_poly_interior: THREE.MeshStandardMaterial;
  };
};

export function Room15(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/room/room15.glb") as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <OrthographicCamera
        makeDefault={true}
        far={1000}
        near={0.1}
        position={[3.86, 3.24, 4.02]}
        rotation={[-0.68, 0.66, 0.46]}
        zoom={92}
      />
      <pointLight
        intensity={0.5}
        decay={2}
        color="#ff4977"
        position={[0.4, 0.25, 1.62]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <directionalLight
        intensity={0.5}
        // decay={2}
        color="#ffdfb6"
        position={[-21.11, 1.89, 10.85]}
        rotation={[-1.06, -0.39, -0.62]}
      />
      <mesh
        geometry={nodes.low_poly_interior465.geometry}
        material={materials.emit}
        position={[0, -2, 0]}
      />
      <mesh
        geometry={nodes.low_poly_interior466.geometry}
        material={materials.emit}
        position={[-1.95, 0.31, 1.15]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.low_poly_interior467.geometry}
        material={materials.emit}
        position={[-1.77, 0.15, -1.32]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.low_poly_interior7981.geometry}
        material={materials.low_poly_interior}
        position={[0, -2, 0]}
      />
      <mesh
        geometry={nodes.low_poly_interior7983.geometry}
        material={materials.low_poly_interior}
        position={[-1.39, -1.97, 0.57]}
        rotation={[0, 0.31, 0]}
      />
      <mesh
        geometry={nodes.low_poly_interior7984.geometry}
        material={materials.low_poly_interior}
        position={[-1.67, -0.49, -1.68]}
        rotation={[0, -1.52, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.low_poly_interior7985.geometry}
        material={materials.low_poly_interior}
        position={[-1.71, -2, -0.55]}
        rotation={[0, 0.46, 0]}
      />
      <mesh
        geometry={nodes.low_poly_interior7986.geometry}
        material={materials.low_poly_interior}
        position={[-1.79, -0.45, -1.18]}
      />
      <mesh
        geometry={nodes.low_poly_interior7987.geometry}
        material={materials.low_poly_interior}
        position={[-1.81, -1.14, -0.83]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.low_poly_interior7988.geometry}
        material={materials.low_poly_interior}
        position={[-2.02, -0.38, 1.15]}
      />
      <mesh
        geometry={nodes.low_poly_interior7989.geometry}
        material={materials.low_poly_interior}
        position={[-1.77, -1.64, 0.67]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.low_poly_interior7990.geometry}
        material={materials.low_poly_interior}
        position={[-1.85, -1, 0.63]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.low_poly_interior7993.geometry}
        material={materials.low_poly_interior}
        position={[-1.77, 0.15, -1.32]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.low_poly_interior7994.geometry}
        material={materials.low_poly_interior}
        position={[-1.85, -0.83, -0.67]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.low_poly_interior7995.geometry}
        material={materials.low_poly_interior}
        position={[1.01, -1.16, -1.27]}
        rotation={[-Math.PI, 0.8, -Math.PI]}
      />
      <mesh
        geometry={nodes.low_poly_interior7996.geometry}
        material={materials.low_poly_interior}
        position={[-1.75, -1.74, 1.39]}
        rotation={[0.14, -1.56, 0]}
      />
      <mesh
        geometry={nodes.low_poly_interior7997.geometry}
        material={materials.low_poly_interior}
        position={[-1.74, -0.96, -1.18]}
        rotation={[Math.PI, -1.29, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.low_poly_interior7998.geometry}
        material={materials.low_poly_interior}
        position={[-2.03, 0.92, -1.13]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.low_poly_interior7999.geometry}
        material={materials.low_poly_interior}
        position={[-2.04, -0.93, 0.47]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.low_poly_interior8000.geometry}
        material={materials.low_poly_interior}
        position={[-1.67, -0.79, -0.42]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.low_poly_interior8001.geometry}
        material={materials.low_poly_interior}
        position={[-1.78, -1.32, -0.65]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.low_poly_interior8002.geometry}
        material={materials.low_poly_interior}
        position={[-1.77, -1.5, 1.61]}
        rotation={[Math.PI / 2, 0, Math.PI / 9]}
      />
      <mesh
        geometry={nodes.low_poly_interior8003.geometry}
        material={materials.low_poly_interior}
        position={[-1.95, 0.31, 1.15]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.low_poly_interior8004.geometry}
        material={materials.low_poly_interior}
        position={[-1.92, 1.33, -1.82]}
        rotation={[Math.PI / 2, 0, 2.74]}
      />
      <mesh
        geometry={nodes.low_poly_interior8005.geometry}
        material={materials.low_poly_interior}
        position={[-1.98, 0.13, 0.97]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.low_poly_interior8006.geometry}
        material={materials.low_poly_interior}
        position={[-1.96, 0.09, 0.91]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.low_poly_interior8007.geometry}
        material={materials.low_poly_interior}
        position={[-1.74, -1.75, 0.82]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.low_poly_interior8008.geometry}
        material={materials.low_poly_interior}
        position={[-1.85, -1.3, 0.77]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.low_poly_interior8009.geometry}
        material={materials.low_poly_interior}
        position={[-1.78, -1.32, 0.84]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.low_poly_interior8010.geometry}
        material={materials.low_poly_interior}
        position={[0.26, 5.96, -1.26]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.low_poly_interior8011.geometry}
        material={materials.low_poly_interior}
        position={[0.22, -1.36, 0.47]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.low_poly_interior8012.geometry}
        material={materials.low_poly_interior}
        position={[-1.71, -1.39, 0.12]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.low_poly_interior8013.geometry}
        material={materials.low_poly_interior}
        position={[-1.77, -1.12, 1.07]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.low_poly_interior8014.geometry}
        material={materials.low_poly_interior}
        position={[0.08, -0.87, -0.43]}
        rotation={[Math.PI / 2, 0, 3.14]}
      />
      <mesh
        geometry={nodes.low_poly_interior8015.geometry}
        material={materials.low_poly_interior}
        position={[0.57, -1.99, 1.21]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.low_poly_interior8016.geometry}
        material={materials.low_poly_interior}
        position={[-2.03, -2, -1.99]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.low_poly_interior8017.geometry}
        material={materials.low_poly_interior}
        position={[1.82, 1.33, -1.85]}
        rotation={[Math.PI / 2, 0, -2.88]}
      />
      <mesh
        geometry={nodes.low_poly_interior8018.geometry}
        material={materials.low_poly_interior}
        position={[-1.77, -0.41, -0.58]}
        rotation={[-Math.PI, 0.06, -Math.PI]}
      />
      <mesh
        geometry={nodes.low_poly_interior8019.geometry}
        material={materials.low_poly_interior}
        position={[-1.7, -1.32, -1.69]}
        rotation={[Math.PI / 2, 0, -1.33]}
      />
      <mesh
        geometry={nodes.low_poly_interior8020.geometry}
        material={materials.low_poly_interior}
        position={[-1.87, -1.37, -1.03]}
        rotation={[0, -0.4, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.low_poly_interior8021.geometry}
        material={materials.low_poly_interior}
        position={[-1.75, -1.87, -1.61]}
        rotation={[0.14, -1.56, 0]}
      />
      <mesh
        geometry={nodes.low_poly_interior8022.geometry}
        material={materials.low_poly_interior}
        position={[-1.96, 0.02, -1.81]}
        rotation={[Math.PI, -0.44, Math.PI]}
      />
      <mesh
        geometry={nodes.low_poly_interior8023.geometry}
        material={materials.low_poly_interior}
        position={[-1.79, 0.13, -1.04]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
    </group>
  );
}

useGLTF.preload("/models/room/room15.glb");
