/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/big_car_1.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Alfa_Spider: THREE.Mesh;
    Mesh_1: THREE.Mesh;
    Mesh_2: THREE.Mesh;
    Mesh_3: THREE.Mesh;
    Mesh_4: THREE.Mesh;
    Circle003: THREE.Mesh;
    Circle004: THREE.Mesh;
    Circle005: THREE.Mesh;
    Circle006: THREE.Mesh;
    Circle007: THREE.Mesh;
    Circle029: THREE.Mesh;
    Mesh_32: THREE.Mesh;
    Mesh_33: THREE.Mesh;
    Circle008: THREE.Mesh;
    Circle009: THREE.Mesh;
    Circle010: THREE.Mesh;
    Circle011: THREE.Mesh;
    Circle012: THREE.Mesh;
    Circle013: THREE.Mesh;
    Circle014: THREE.Mesh;
    Mesh_17: THREE.Mesh;
    Mesh_18: THREE.Mesh;
    Mesh_19: THREE.Mesh;
    Mesh_20: THREE.Mesh;
    Circle017: THREE.Mesh;
    Circle018: THREE.Mesh;
    Circle019: THREE.Mesh;
    Circle020: THREE.Mesh;
    Circle021: THREE.Mesh;
    Circle022: THREE.Mesh;
    Circle023: THREE.Mesh;
    Circle024: THREE.Mesh;
    Circle025: THREE.Mesh;
    Circle026: THREE.Mesh;
    Circle030: THREE.Mesh;
    Cube: THREE.Mesh;
    Cylinder: THREE.Mesh;
    Cylinder001: THREE.Mesh;
    Plane: THREE.Mesh;
    Plane001: THREE.Mesh;
    Plane001_1: THREE.Mesh;
    Plane001_2: THREE.Mesh;
    Plane001_3: THREE.Mesh;
    Plane003: THREE.Mesh;
    Plane004: THREE.Mesh;
    Plane005: THREE.Mesh;
  };
  materials: {
    Car: THREE.MeshStandardMaterial;
    summer_tire_f_sculpts_tread: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    leather_fine: THREE.MeshStandardMaterial;
    Chrome: THREE.MeshStandardMaterial;
    ["Black Plastic"]: THREE.MeshStandardMaterial;
    Logo: THREE.MeshStandardMaterial;
    Glass: THREE.MeshPhysicalMaterial;
    ["Turn Light"]: THREE.MeshPhysicalMaterial;
    burma_padauk_wood_varnished: THREE.MeshStandardMaterial;
    Metal: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["Rear Light"]: THREE.MeshPhysicalMaterial;
    ["Rear Light.001"]: THREE.MeshPhysicalMaterial;
  };
};

export function Big_car_1(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/items/big_car_1.glb"
  ) as GLTFResult;

  console.log(nodes);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Alfa_Spider.geometry}
        material={materials.Car}
        position={[0, 0.16, -0.09]}
        scale={1.54}
      >
        <group position={[0.84, 0.34, 1.26]}>
          <mesh
            geometry={nodes.Mesh_1.geometry}
            material={materials.summer_tire_f_sculpts_tread}
          />
          <mesh
            geometry={nodes.Mesh_2.geometry}
            material={materials["Material.001"]}
          />
        </group>
        <group position={[0.84, 0.34, -1.28]}>
          <mesh
            // geometry={nodes.Mesh_3.geometry}
            material={materials.summer_tire_f_sculpts_tread}
          />
          <mesh
            geometry={nodes.Mesh_4.geometry}
            material={materials["Material.001"]}
          />
        </group>
        <mesh
          geometry={nodes.Circle003.geometry}
          material={materials.leather_fine}
        />
        <mesh geometry={nodes.Circle004.geometry} material={materials.Car} />
        <mesh geometry={nodes.Circle005.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Circle006.geometry} material={materials.Chrome} />
        <mesh
          geometry={nodes.Circle007.geometry}
          material={materials["Black Plastic"]}
        >
          <mesh
            geometry={nodes.Circle029.geometry}
            material={materials.Chrome}
          />
          <group position={[0, 0.48, 2.34]} rotation={[0.3, 0, 0]} scale={0.08}>
            {/* <mesh geometry={nodes.Mesh_32.geometry} material={materials.Logo} /> */}
            <mesh
              // geometry={nodes.Mesh_33.geometry}
              material={materials.Chrome}
            />
          </group>
        </mesh>
        <mesh
          geometry={nodes.Circle008.geometry}
          material={materials["Black Plastic"]}
        />
        <mesh
          geometry={nodes.Circle009.geometry}
          material={materials["Black Plastic"]}
        />
        <mesh geometry={nodes.Circle010.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Circle011.geometry} material={materials.Glass} />
        <mesh
          geometry={nodes.Circle012.geometry}
          material={materials["Turn Light"]}
        />
        <mesh geometry={nodes.Circle013.geometry} material={materials.Chrome} />
        <mesh
          geometry={nodes.Circle014.geometry}
          material={materials["Black Plastic"]}
        />
        <group position={[0.84, 0.34, 1.26]} scale={1.07}>
          {/* <mesh geometry={nodes.Mesh_17.geometry} material={materials.Chrome} /> */}
          <mesh
            // geometry={nodes.Mesh_18.geometry}
            material={materials["Black Plastic"]}
          />
        </group>
        <group position={[0.84, 0.34, -1.28]} scale={1.07}>
          {/* <mesh geometry={nodes.Mesh_19.geometry} material={materials.Chrome} /> */}
          <mesh
            // geometry={nodes.Mesh_20.geometry}
            material={materials["Black Plastic"]}
          />
        </group>
        <mesh geometry={nodes.Circle017.geometry} material={materials.Car} />
        <mesh
          geometry={nodes.Circle018.geometry}
          material={materials.leather_fine}
        />
        <mesh
          geometry={nodes.Circle019.geometry}
          material={materials.leather_fine}
          position={[0.07, 0, 0.11]}
        />
        <mesh
          geometry={nodes.Circle020.geometry}
          material={materials.burma_padauk_wood_varnished}
          position={[0.4, 0.94, 0.16]}
          rotation={[-1.26, 0, 0]}
          scale={1.12}
        />
        <mesh
          geometry={nodes.Circle021.geometry}
          material={materials.Metal}
          position={[0.4, 0.94, 0.16]}
          rotation={[-1.26, 0, 0]}
          scale={1.12}
        />
        <mesh
          geometry={nodes.Circle022.geometry}
          material={materials.leather_fine}
        />
        <mesh geometry={nodes.Circle023.geometry} material={materials.Chrome} />
        <mesh
          geometry={nodes.Circle024.geometry}
          material={materials["Black Plastic"]}
          position={[0.78, 0.89, 0.22]}
          rotation={[-0.27, 0, 0.26]}
          scale={1.08}
        />
        <mesh
          geometry={nodes.Circle025.geometry}
          material={materials["Black Plastic"]}
          position={[0.54, 0.95, 0.59]}
          rotation={[0.63, 0.04, -0.11]}
          scale={1.31}
        />
        <mesh
          geometry={nodes.Circle026.geometry}
          material={materials["Black Plastic"]}
          position={[-0.07, 0.98, 0.7]}
          rotation={[0.61, -0.29, 0.23]}
          scale={1.31}
        />
        <mesh geometry={nodes.Circle030.geometry} material={materials.Glass} />
        <mesh
          geometry={nodes.Cube.geometry}
          material={materials["Black Plastic"]}
          position={[0.82, 0.99, 0.17]}
          rotation={[0, 0.37, 0]}
          scale={1.13}
        />
        <mesh
          geometry={nodes.Cylinder.geometry}
          material={materials["default"]}
          position={[0.4, 0.84, 0.47]}
          rotation={[-1.29, 0, 0]}
          scale={1.12}
        />
        <mesh
          geometry={nodes.Cylinder001.geometry}
          material={materials.leather_fine}
          position={[0.4, 0.92, 0.21]}
          rotation={[-1.26, 0, 0]}
          scale={1.12}
        />
        <mesh
          geometry={nodes.Plane.geometry}
          material={materials["Black Plastic"]}
          position={[0.25, 1, 0.64]}
          rotation={[0.66, 0.31, -0.11]}
          scale={1.31}
        />
        <mesh
          geometry={nodes.Plane001.geometry}
          material={materials["Black Plastic"]}
          position={[-0.35, 1, 0.61]}
          rotation={[0.55, -0.02, 0.22]}
          scale={1.31}
        />
        <group position={[0.6, 0.74, -2.21]}>
          <mesh
            geometry={nodes.Plane001_1.geometry}
            material={materials["Rear Light"]}
          />
          <mesh
            geometry={nodes.Plane001_2.geometry}
            material={materials["Rear Light.001"]}
          />
          <mesh
            geometry={nodes.Plane001_3.geometry}
            material={materials.Glass}
          />
        </group>
        <mesh
          geometry={nodes.Plane003.geometry}
          material={materials.Metal}
          position={[0, 0.74, -2.21]}
        />
        <mesh
          geometry={nodes.Plane004.geometry}
          material={materials.leather_fine}
          position={[0.38, 0.42, -0.18]}
        />
        <mesh
          geometry={nodes.Plane005.geometry}
          material={materials.leather_fine}
          position={[0.38, 0.4, -0.45]}
          rotation={[-0.21, 0, 0]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/items/big_car_1.glb");
