/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/blue_chair_2.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    chair001: THREE.Mesh;
    BezierCircle: THREE.Mesh;
    Vert001: THREE.Mesh;
    Vert002: THREE.Mesh;
    Vert003: THREE.Mesh;
  };
  materials: {
    Red: THREE.MeshStandardMaterial;
    Metal: THREE.MeshStandardMaterial;
  };
};

export function Blue_chair_2(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/items/blue_chair_2.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, -2.5, 0]}>
      <mesh
        geometry={nodes.chair001.geometry}
        material={materials.Red}
        position={[0, 0, 0]}
        rotation={[0, -0.45, 0]}
        scale={1.3}
      >
        <mesh
          geometry={nodes.BezierCircle.geometry}
          material={materials.Metal}
          position={[0, 0.61, 0]}
        />
        <mesh geometry={nodes.Vert001.geometry} material={materials.Metal} />
        <mesh
          geometry={nodes.Vert002.geometry}
          material={materials.Metal}
          position={[0, 0.77, 0]}
          scale={0.99}
        />
        <mesh
          geometry={nodes.Vert003.geometry}
          material={materials.Red}
          position={[0, 0.77, 0]}
          scale={0.99}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/items/blue_chair_2.glb");
