/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/blue_car_1.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Car_Model001: THREE.Mesh;
    Mesh_1: THREE.Mesh;
    Mesh_2: THREE.Mesh;
    Circle034: THREE.Mesh;
    Circle035: THREE.Mesh;
    Circle036: THREE.Mesh;
    Circle037: THREE.Mesh;
    Circle038: THREE.Mesh;
    Circle039: THREE.Mesh;
    Circle040: THREE.Mesh;
    Circle041: THREE.Mesh;
    Circle043: THREE.Mesh;
    Circle044: THREE.Mesh;
    Circle045: THREE.Mesh;
    Mesh_14: THREE.Mesh;
    Mesh_15: THREE.Mesh;
    Mesh_16: THREE.Mesh;
    Mesh_17: THREE.Mesh;
    Mesh_18: THREE.Mesh;
    Mesh_19: THREE.Mesh;
    Circle049: THREE.Mesh;
    Circle050: THREE.Mesh;
    Circle051: THREE.Mesh;
    Circle052: THREE.Mesh;
    Circle054: THREE.Mesh;
    Circle055: THREE.Mesh;
    Circle056: THREE.Mesh;
    Circle060: THREE.Mesh;
    Cube006: THREE.Mesh;
    Cylinder002: THREE.Mesh;
    Cylinder003: THREE.Mesh;
    Plane001: THREE.Mesh;
    Plane001_1: THREE.Mesh;
    Plane001_2: THREE.Mesh;
    Plane028: THREE.Mesh;
    Plane029: THREE.Mesh;
  };
  materials: {
    ["Car.001"]: THREE.MeshStandardMaterial;
    summer_tire_f_sculpts_tread: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    Chrome: THREE.MeshStandardMaterial;
    ["Black Plastic"]: THREE.MeshStandardMaterial;
    Glass: THREE.MeshPhysicalMaterial;
    leather_fine: THREE.MeshStandardMaterial;
    burma_padauk_wood_varnished: THREE.MeshStandardMaterial;
    Metal: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["Rear Light"]: THREE.MeshPhysicalMaterial;
    ["Rear Light.001"]: THREE.MeshPhysicalMaterial;
  };
};

export function Blue_car_1(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/items/blue_car_1.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Car_Model001.geometry}
        material={materials["Car.001"]}
        position={[0.03, 0.93, 0]}
        scale={0.23}
      >
        <group position={[0.84, 0.34, 1.26]}>
          <mesh
            geometry={nodes.Mesh_1.geometry}
            material={materials.summer_tire_f_sculpts_tread}
          />
          <mesh
            geometry={nodes.Mesh_2.geometry}
            material={materials["Material.001"]}
          />
        </group>
        <mesh
          geometry={nodes.Circle034.geometry}
          material={materials["Car.001"]}
        />
        <mesh geometry={nodes.Circle035.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Circle036.geometry} material={materials.Chrome} />
        <mesh
          geometry={nodes.Circle037.geometry}
          material={materials["Black Plastic"]}
        />
        <mesh
          geometry={nodes.Circle038.geometry}
          material={materials["Black Plastic"]}
        />
        <mesh
          geometry={nodes.Circle039.geometry}
          material={materials["Black Plastic"]}
        />
        <mesh geometry={nodes.Circle040.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Circle041.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Circle043.geometry} material={materials.Chrome} />
        <mesh
          geometry={nodes.Circle044.geometry}
          material={materials["Black Plastic"]}
        />
        <mesh
          geometry={nodes.Circle045.geometry}
          material={materials.leather_fine}
        />
        <group position={[0.84, 0.34, 1.26]} scale={1.07}>
          <mesh geometry={nodes.Mesh_14.geometry} material={materials.Chrome} />
          <mesh
            geometry={nodes.Mesh_15.geometry}
            material={materials["Black Plastic"]}
          />
        </group>
        <group position={[0.84, 0.34, -1.28]}>
          <mesh
            geometry={nodes.Mesh_16.geometry}
            material={materials.summer_tire_f_sculpts_tread}
          />
          <mesh
            geometry={nodes.Mesh_17.geometry}
            material={materials["Material.001"]}
          />
        </group>
        <group position={[0.84, 0.34, -1.28]} scale={1.07}>
          <mesh geometry={nodes.Mesh_18.geometry} material={materials.Chrome} />
          <mesh
            geometry={nodes.Mesh_19.geometry}
            material={materials["Black Plastic"]}
          />
        </group>
        <mesh
          geometry={nodes.Circle049.geometry}
          material={materials["Car.001"]}
        />
        <mesh
          geometry={nodes.Circle050.geometry}
          material={materials.leather_fine}
        />
        <mesh
          geometry={nodes.Circle051.geometry}
          material={materials.leather_fine}
          position={[0.07, 0, 0.11]}
        />
        <mesh
          geometry={nodes.Circle052.geometry}
          material={materials.leather_fine}
        />
        <mesh
          geometry={nodes.Circle054.geometry}
          material={materials["Black Plastic"]}
          position={[0.78, 0.89, 0.22]}
          rotation={[-0.27, 0, 0.26]}
          scale={1.08}
        />
        <mesh
          geometry={nodes.Circle055.geometry}
          material={materials.burma_padauk_wood_varnished}
          position={[0.4, 0.94, 0.16]}
          rotation={[-1.26, 0, 0]}
          scale={1.12}
        />
        <mesh
          geometry={nodes.Circle056.geometry}
          material={materials.Metal}
          position={[0.4, 0.94, 0.16]}
          rotation={[-1.26, 0, 0]}
          scale={1.12}
        />
        <mesh geometry={nodes.Circle060.geometry} material={materials.Glass} />
        <mesh
          geometry={nodes.Cube006.geometry}
          material={materials["Black Plastic"]}
          position={[0.82, 0.99, 0.17]}
          rotation={[0, 0.37, 0]}
          scale={1.13}
        />
        <mesh
          geometry={nodes.Cylinder002.geometry}
          material={materials.leather_fine}
          position={[0.4, 0.92, 0.21]}
          rotation={[-1.26, 0, 0]}
          scale={1.12}
        />
        <mesh
          geometry={nodes.Cylinder003.geometry}
          material={materials["default"]}
          position={[0.4, 0.84, 0.47]}
          rotation={[-1.29, 0, 0]}
          scale={1.12}
        />
        <group position={[0.6, 0.74, -2.21]}>
          <mesh
            geometry={nodes.Plane001.geometry}
            material={materials["Rear Light"]}
          />
          <mesh
            geometry={nodes.Plane001_1.geometry}
            material={materials["Rear Light.001"]}
          />
          <mesh
            geometry={nodes.Plane001_2.geometry}
            material={materials.Glass}
          />
        </group>
        <mesh
          geometry={nodes.Plane028.geometry}
          material={materials.leather_fine}
          position={[0.38, 0.42, -0.18]}
        />
        <mesh
          geometry={nodes.Plane029.geometry}
          material={materials.leather_fine}
          position={[0.38, 0.4, -0.45]}
          rotation={[-0.21, 0, 0]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/items/blue_car_1.glb");
