/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/coffee_cup_1.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cup001: THREE.Mesh;
    Circle094: THREE.Mesh;
    Cup002: THREE.Mesh;
  };
  materials: {
    ["White.002"]: THREE.MeshStandardMaterial;
    ["Black.001"]: THREE.MeshStandardMaterial;
  };
};

export function Coffee_cup_1(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/items/coffee_cup_1.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, -3.35, 0]}>
      <mesh
        geometry={nodes.Cup001.geometry}
        material={materials["White.002"]}
        position={[0.03, 0.9, -0.01]}
        rotation={[0, -0.84, 0]}
        scale={0.77}
      >
        <mesh
          geometry={nodes.Circle094.geometry}
          material={materials["White.002"]}
          position={[-0.01, -0.04, -0.01]}
          rotation={[0, 1.03, 0]}
          scale={1.03}
        />
        <mesh
          geometry={nodes.Cup002.geometry}
          material={materials["Black.001"]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/items/coffee_cup_1.glb");
