/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/elec_guitar_1.glb -t
*/

import * as THREE from "three";
import React, { useRef, useState, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useRecoilState } from "recoil";
import { itemTargetState, myItemsState } from "@/recoil/myroom/atoms";
import { useFrame, useThree } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    Stand002: THREE.Mesh;
    Vert032: THREE.Mesh;
    Circle031: THREE.Mesh;
    Circle032: THREE.Mesh;
    Circle033: THREE.Mesh;
    Circle034: THREE.Mesh;
    Circle035: THREE.Mesh;
    Cylinder059: THREE.Mesh;
    Cylinder060: THREE.Mesh;
    Cylinder061: THREE.Mesh;
    Cylinder062: THREE.Mesh;
    Plane087: THREE.Mesh;
    Plane088: THREE.Mesh;
    Plane089: THREE.Mesh;
    Plane090: THREE.Mesh;
    Vert034: THREE.Mesh;
  };
  materials: {
    Black: THREE.MeshStandardMaterial;
    ["Red.001"]: THREE.MeshStandardMaterial;
    Gold: THREE.MeshStandardMaterial;
    Chrome: THREE.MeshStandardMaterial;
    ["Black.002"]: THREE.MeshStandardMaterial;
    ["Metal.001"]: THREE.MeshStandardMaterial;
  };
};

export function Elec_guitar_1(props: JSX.IntrinsicElements["group"] | any) {
  const { nodes, materials } = useGLTF(
    "/models/items/elec_guitar_1.glb"
  ) as GLTFResult;

  const [propsX, propsY, propsZ] = props.position;
  const propsDeg = props.deg;

  // 좌표 (서버에 저장된 좌표로 수정하기)
  const [position, setPosition] = useState({ x: propsX, y: propsY, z: propsZ });
  const [isDragging, setIsDragging] = useState(false);

  // 회전 정보 (서버에 저장된 좌표로 수정하기)
  const [rotation, setRotation] = useState(propsDeg);

  // 타겟 정보
  const [target, setTarget] = useRecoilState(itemTargetState);

  const { scene, camera, gl } = useThree();
  const raycaster = new THREE.Raycaster();

  function intersect(pos: THREE.Vector2) {
    raycaster.setFromCamera(pos, camera);
    return raycaster.intersectObjects(scene.children);
  }

  const [myItems, setMyItems] = useRecoilState(myItemsState);

  const updateTagetItemPosition = (
    id: number,
    x: number,
    y: number,
    z: number,
    deg: number
  ) => {
    myItems.forEach((item, i) => {
      // itemId가 일치하는 아이템 선별
      if (item.itemId === id) {
        // 변화된 포지션 저장
        let newItemPosition = {
          ...item,
          x,
          y,
          z,
          deg,
        };
        // 불변성 유지를 위한 새로운 배열 생성
        const newItems = [...myItems];
        newItems[i] = newItemPosition;

        // 새로운 배열을 atom에 저장
        setMyItems(newItems);
      }
    });
  };

  useEffect(() => {
    const handleWindowClick = (e: MouseEvent) => {
      if (isDragging) {
        setIsDragging(false);
      }
    };

    if (props.activePage === "myitems") {
      gl.domElement.addEventListener("click", handleWindowClick);

      // atom에 변화된 포지션 저장
      updateTagetItemPosition(
        props.itemId,
        position.x,
        position.y,
        position.z,
        rotation
      );
    }

    return () => {
      if (props.activePage === "myitems") {
        gl.domElement.removeEventListener("click", handleWindowClick);
      }
    };
  }, [isDragging]);

  useFrame(({ mouse }) => {
    if (props.activePage === "myitems") {
      if (isDragging) {
        const found = intersect(mouse);

        if (found.length > 0) {
          for (let i = 0; i < found.length; i++) {
            if (!found[i].object.userData.ground) continue;

            // 물체가 마우스와 만난 지점으로 위치를 업데이트하기
            const newPosition = found[i].point;
            setPosition({ x: newPosition.x, y: position.y, z: newPosition.z });
            break;
          }
        }
      }
    }
  });

  // 물체 회전
  if (
    props.rotationLeftButtonRef.current &&
    props.rotationRigthButtonRef.current &&
    props.upButtonRef.current &&
    props.downButtonRef.current
  ) {
    const leftRotation = () => {
      let newRotation = (rotation - 10) % 360;
      setRotation(newRotation);
    };

    const rightRotation = () => {
      let newRotation = (rotation + 10) % 360;
      setRotation(newRotation);
    };

    const positionUp = () => {
      if (position.y < 3) {
        const newY = position.y + 0.2;
        setPosition({ x: position.x, y: newY, z: position.z });
      }
    };

    const positionDown = () => {
      if (position.y > -2.5) {
        const newY = position.y - 0.2;
        setPosition({ x: position.x, y: newY, z: position.z });
      }
    };

    if (target === "Elec_guitar_1") {
      props.rotationLeftButtonRef.current.addEventListener(
        "click",
        leftRotation
      );
      props.rotationRigthButtonRef.current.addEventListener(
        "click",
        rightRotation
      );
      props.upButtonRef.current.addEventListener("click", positionUp);
      props.downButtonRef.current.addEventListener("click", positionDown);
    } else {
      props.rotationLeftButtonRef.current.removeEventListener(
        "click",
        leftRotation
      );
      props.rotationRigthButtonRef.current.removeEventListener(
        "click",
        rightRotation
      );
    }
  }

  return (
    <group
      {...props}
      dispose={null}
      position={[position.x, position.y, position.z]}
      userData={{ draggable: true, name: "Elec_guitar_1" }}
      onClick={() => {
        if (props.activePage === "myitems") {
          if (!isDragging) setIsDragging(true);
          setTarget("Elec_guitar_1");
        }
      }}
      rotation={[0, THREE.MathUtils.degToRad(rotation), 0]}
    >
      <mesh
        geometry={nodes.Stand002.geometry}
        material={materials.Black}
        scale={1.04}
      >
        <mesh
          geometry={nodes.Vert032.geometry}
          material={materials["Red.001"]}
          position={[0.01, 1.15, 0]}
          rotation={[-Math.PI, 0, -1.8]}
          scale={1.12}
        >
          <mesh
            geometry={nodes.Circle031.geometry}
            material={materials.Gold}
            position={[-0.58, 0.01, 0.16]}
          />
          <mesh
            geometry={nodes.Circle032.geometry}
            material={materials.Gold}
            position={[-0.52, 0.01, 0.27]}
          />
          <mesh
            geometry={nodes.Circle033.geometry}
            material={materials.Gold}
            position={[-0.71, 0.01, 0.15]}
          />
          <mesh
            geometry={nodes.Circle034.geometry}
            material={materials.Gold}
            position={[-0.66, 0.01, 0.26]}
          />
          <mesh
            geometry={nodes.Circle035.geometry}
            material={materials.Gold}
            position={[-0.04, 0.02, -0.16]}
          />
          <mesh
            geometry={nodes.Cylinder059.geometry}
            material={materials.Chrome}
            position={[-0.04, 0.02, -0.16]}
          />
          <mesh
            geometry={nodes.Cylinder060.geometry}
            material={materials.Gold}
            position={[1.08, 0, -0.07]}
          />
          <mesh
            geometry={nodes.Cylinder061.geometry}
            material={materials.Gold}
            position={[1.15, -0.01, -0.07]}
          />
          <mesh
            geometry={nodes.Cylinder062.geometry}
            material={materials.Gold}
            position={[1.22, -0.01, -0.07]}
          />
          <mesh
            geometry={nodes.Plane087.geometry}
            material={materials["Black.002"]}
            position={[0.96, 0.03, 0]}
            rotation={[0, 0, -0.1]}
          />
          <mesh
            geometry={nodes.Plane088.geometry}
            material={materials.Gold}
            position={[-0.14, 0.02, 0]}
          />
          <mesh
            geometry={nodes.Plane089.geometry}
            material={materials.Gold}
            position={[-0.55, 0.02, 0]}
          />
          <mesh
            geometry={nodes.Plane090.geometry}
            material={materials.Gold}
            position={[-0.46, 0.02, 0]}
          />
          <mesh
            geometry={nodes.Vert034.geometry}
            material={materials["Metal.001"]}
            position={[-0.46, 0.04, -0.06]}
          />
        </mesh>
      </mesh>
    </group>
  );
}

// useGLTF.preload("/models/items/elec_guitar_1.glb");
