/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/imac_computer_1.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Monitor001: THREE.Mesh;
    Display: THREE.Mesh;
    Monitor_Stand: THREE.Mesh;
    Keyboard: THREE.Mesh;
    Plane043: THREE.Mesh;
  };
  materials: {
    Steel: THREE.MeshStandardMaterial;
    ["Black.002"]: THREE.MeshStandardMaterial;
    ["Black.001"]: THREE.MeshStandardMaterial;
  };
};

export function Imac_computer_1(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/items/imac_computer_1.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, -4.2, 0]}>
      <mesh
        geometry={nodes.Monitor001.geometry}
        material={materials.Steel}
        position={[0, 1.72, -0.24]}
        scale={1.13}
      >
        <mesh
          geometry={nodes.Display.geometry}
          material={materials["Black.002"]}
        />
        <mesh
          geometry={nodes.Monitor_Stand.geometry}
          material={materials.Steel}
        />
      </mesh>
      <mesh
        geometry={nodes.Keyboard.geometry}
        material={materials.Steel}
        position={[-0.01, 1.72, 0.37]}
        scale={1.09}
      >
        <mesh
          geometry={nodes.Plane043.geometry}
          material={materials["Black.001"]}
          rotation={[0.08, 0, 0]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/items/imac_computer_1.glb");
