/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/marble_table_1.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane007: THREE.Mesh;
    Plane008: THREE.Mesh;
  };
  materials: {
    Marble: THREE.MeshStandardMaterial;
    ["Black.001"]: THREE.MeshStandardMaterial;
  };
};

export function Marble_table_1(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/items/marble_table_1.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane007.geometry}
        material={materials.Marble}
        position={[0.01, 0.03, 0.01]}
      >
        <mesh
          geometry={nodes.Plane008.geometry}
          material={materials["Black.001"]}
          position={[0, 0.14, -0.87]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/items/marble_table_1.glb");
