/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/retro_arcadegame_1.glb -t
*/

import * as THREE from "three";
import React, { useRef, useState, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useRecoilState } from "recoil";
import { itemTargetState } from "@/recoil/myroom/atoms";
import { useFrame, useThree } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    Plane050: THREE.Mesh;
    Plane050_1: THREE.Mesh;
    Plane050_2: THREE.Mesh;
    Plane050_3: THREE.Mesh;
    Plane050_4: THREE.Mesh;
    Plane031: THREE.Mesh;
    Cylinder_1: THREE.Mesh;
    Cylinder_2: THREE.Mesh;
    Plane032: THREE.Mesh;
    // Cylinder_1: THREE.Mesh
    // Cylinder_2: THREE.Mesh
    Plane033: THREE.Mesh;
  };
  materials: {
    black: THREE.MeshStandardMaterial;
    ["screen-arcade"]: THREE.MeshStandardMaterial;
    ["arcade-header"]: THREE.MeshStandardMaterial;
    ["led.001"]: THREE.MeshStandardMaterial;
    ["led.002"]: THREE.MeshStandardMaterial;
    grey: THREE.MeshStandardMaterial;
    ["black-gloss"]: THREE.MeshStandardMaterial;
    red: THREE.MeshStandardMaterial;
    led: THREE.MeshStandardMaterial;
  };
};

export function Retro_arcadegame_1(
  props: JSX.IntrinsicElements["group"] | any
) {
  const { nodes, materials } = useGLTF(
    "/models/items/retro_arcadegame_1.glb"
  ) as GLTFResult;

  // 좌표 (서버에 저장된 좌표로 수정하기)
  const [position, setPosition] = useState({ x: 0, y: -2.5, z: 0 });
  const [isDragging, setIsDragging] = useState(false);

  // 회전 유무 판단
  const [isRotation, setIsRotation] = useState(false);

  // 회전 정보 (서버에 저장된 좌표로 수정하기)
  const [rotation, setRotation] = useState(0);

  // 타겟 정보
  const [target, setTarget] = useRecoilState(itemTargetState);

  const { scene, camera, gl } = useThree();
  const raycaster = new THREE.Raycaster();

  function intersect(pos: THREE.Vector2) {
    raycaster.setFromCamera(pos, camera);
    return raycaster.intersectObjects(scene.children);
  }

  useEffect(() => {
    if (props.activePage === "myitems") {
      gl.domElement.addEventListener("click", () => {
        if (isDragging) {
          setIsDragging(false);
        }
      });
    }

    // const handleWindowClick = (e: MouseEvent) => {
    //   if (isDragging) {
    //     setIsDragging(false);
    //   }
    // };
  }, [isDragging]);

  useFrame(({ mouse }) => {
    if (props.activePage === "myitems") {
      if (isDragging) {
        const found = intersect(mouse);

        if (found.length > 0) {
          for (let i = 0; i < found.length; i++) {
            if (!found[i].object.userData.ground) continue;

            // 물체가 마우스와 만난 지점으로 위치를 업데이트하기
            const newPosition = found[i].point;
            setPosition({ x: newPosition.x, y: -2.5, z: newPosition.z });
            break;
          }
        }
      }
    }
  });

  // 물체 회전
  if (
    props.rotationLeftButtonRef.current &&
    props.rotationRigthButtonRef.current
  ) {
    if (target === "Retro_arcadegame_1") {
      props.rotationLeftButtonRef.current.addEventListener("click", () => {
        setRotation((rotation - 10) % 360);
      });
      props.rotationRigthButtonRef.current.addEventListener("click", () => {
        setRotation((rotation + 10) % 360);
      });
    }
  }

  return (
    <group
      {...props}
      dispose={null}
      scale={0.7}
      position={[position.x, position.y, position.z]}
      userData={{ draggable: true, name: "Retro_arcadegame_1" }}
      onClick={() => {
        if (props.activePage === "myitems") {
          if (!isDragging) setIsDragging(true);
          setTarget("Retro_arcadegame_1");
        }
      }}
      rotation={[0, THREE.MathUtils.degToRad(rotation), 0]}
    >
      <group scale={1.13}>
        <mesh geometry={nodes.Plane050.geometry} material={materials.black} />
        <mesh
          geometry={nodes.Plane050_1.geometry}
          material={materials["screen-arcade"]}
        />
        <mesh
          geometry={nodes.Plane050_2.geometry}
          material={materials["arcade-header"]}
        />
        <mesh
          geometry={nodes.Plane050_3.geometry}
          material={materials["led.001"]}
        />
        <mesh
          geometry={nodes.Plane050_4.geometry}
          material={materials["led.002"]}
        />
        <mesh
          geometry={nodes.Plane031.geometry}
          material={materials.grey}
          position={[0.64, 1.92, 0.46]}
          rotation={[0, 0, -0.27]}
          scale={0.69}
        >
          <group position={[0, 0.08, 0]} scale={1.45}>
            <mesh
              geometry={nodes.Cylinder_1.geometry}
              material={materials["black-gloss"]}
            />
            <mesh
              geometry={nodes.Cylinder_2.geometry}
              material={materials.red}
            />
          </group>
        </mesh>
        <mesh
          geometry={nodes.Plane032.geometry}
          material={materials.grey}
          position={[0.64, 1.92, -0.3]}
          rotation={[0, 0, -0.27]}
          scale={0.69}
        >
          <group position={[0, 0.08, 0]} scale={1.45}>
            <mesh
              geometry={nodes.Cylinder_1.geometry}
              material={materials["black-gloss"]}
            />
            <mesh
              geometry={nodes.Cylinder_2.geometry}
              material={materials.red}
            />
          </group>
        </mesh>
        <mesh geometry={nodes.Plane033.geometry} material={materials.led} />
      </group>
    </group>
  );
}

useGLTF.preload("/models/items/retro_arcadegame_1.glb");
