/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/white_skeleton_1.glb -t
*/

import * as THREE from "three";
import React, { useRef, useState, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useRecoilState } from "recoil";
import { itemTargetState } from "@/recoil/myroom/atoms";
import { useFrame, useThree } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    Skeleton: THREE.Mesh;
    Plane031: THREE.SkinnedMesh;
    Plane031_1: THREE.SkinnedMesh;
    Plane031_2: THREE.SkinnedMesh;
    Plane031_3: THREE.SkinnedMesh;
    Plane031_4: THREE.SkinnedMesh;
    root: THREE.Bone;
    neutral_bone: THREE.Bone;
  };
  materials: {
    Bronze: THREE.MeshStandardMaterial;
    skull: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
  };
};

export function White_skeleton_1(props: JSX.IntrinsicElements["group"] | any) {
  const { nodes, materials } = useGLTF(
    "/models/items/white_skeleton_1.glb"
  ) as GLTFResult;

  // 좌표 (서버에 저장된 좌표로 수정하기)
  const [position, setPosition] = useState({ x: 0, y: -2.5, z: 0 });
  const [isDragging, setIsDragging] = useState(false);

  // 회전 유무 판단
  const [isRotation, setIsRotation] = useState(false);

  // 회전 정보 (서버에 저장된 좌표로 수정하기)
  const [rotation, setRotation] = useState(0);

  // 타겟 정보
  const [target, setTarget] = useRecoilState(itemTargetState);

  const { scene, camera, gl } = useThree();
  const raycaster = new THREE.Raycaster();

  function intersect(pos: THREE.Vector2) {
    raycaster.setFromCamera(pos, camera);
    return raycaster.intersectObjects(scene.children);
  }

  useEffect(() => {
    if (props.activePage === "myitems") {
      gl.domElement.addEventListener("click", () => {
        if (isDragging) {
          setIsDragging(false);
        }
      });
    }

    // const handleWindowClick = (e: MouseEvent) => {
    //   if (isDragging) {
    //     setIsDragging(false);
    //   }
    // };
  }, [isDragging]);

  useFrame(({ mouse }) => {
    if (props.activePage === "myitems") {
      if (isDragging) {
        const found = intersect(mouse);

        if (found.length > 0) {
          for (let i = 0; i < found.length; i++) {
            if (!found[i].object.userData.ground) continue;

            // 물체가 마우스와 만난 지점으로 위치를 업데이트하기
            const newPosition = found[i].point;
            setPosition({ x: newPosition.x, y: -2.5, z: newPosition.z });
            break;
          }
        }
      }
    }
  });

  // 물체 회전
  if (
    props.rotationLeftButtonRef.current &&
    props.rotationRigthButtonRef.current
  ) {
    if (target === "White_skeleton_1") {
      props.rotationLeftButtonRef.current.addEventListener("click", () => {
        setRotation((rotation - 10) % 360);
      });
      props.rotationRigthButtonRef.current.addEventListener("click", () => {
        setRotation((rotation + 10) % 360);
      });
    }
  }

  return (
    <group
      {...props}
      dispose={null}
      scale={0.7}
      position={[position.x, position.y, position.z]}
      userData={{ draggable: true, name: "White_skeleton_1" }}
      onClick={() => {
        if (props.activePage === "myitems") {
          if (!isDragging) setIsDragging(true);
          setTarget("White_skeleton_1");
        }
      }}
      rotation={[0, THREE.MathUtils.degToRad(rotation), 0]}
    >
      <mesh
        geometry={nodes.Skeleton.geometry}
        material={materials.Bronze}
        scale={1.21}
      >
        <group position={[0, -0.02, 0]} rotation={[0, 1.57, 0]} scale={1.85}>
          <primitive object={nodes.root} />
          <primitive object={nodes.neutral_bone} />
          <skinnedMesh
            geometry={nodes.Plane031.geometry}
            material={materials.skull}
            skeleton={nodes.Plane031.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Plane031_1.geometry}
            material={materials["Material.001"]}
            skeleton={nodes.Plane031_1.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Plane031_2.geometry}
            material={materials["default"]}
            skeleton={nodes.Plane031_2.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Plane031_3.geometry}
            material={materials["Material.003"]}
            skeleton={nodes.Plane031_3.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Plane031_4.geometry}
            material={materials["Material.004"]}
            skeleton={nodes.Plane031_4.skeleton}
          />
        </group>
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/items/white_skeleton_1.glb");
