/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/itemShop/chair.glb -t
*/

import * as THREE from "three";
import React, { useEffect, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame, useThree } from "@react-three/fiber";
import { useRecoilState } from "recoil";
import { itemTargetState } from "@/recoil/myroom/atoms";

type GLTFResult = GLTF & {
  nodes: {
    Chair: THREE.Mesh;
    Circle: THREE.Mesh;
  };
  materials: {
    White: THREE.MeshStandardMaterial;
    Wood2: THREE.MeshStandardMaterial;
  };
};

export function ChairEdit(props: JSX.IntrinsicElements["group"] | any) {
  const { nodes, materials } = useGLTF(
    "/models/items/white_chair_1.glb"
  ) as GLTFResult;

  // 좌표 (서버에 저장된 좌표로 수정하기)
  const [position, setPosition] = useState({ x: 0, y: -2.5, z: 0 });
  const [isDragging, setIsDragging] = useState(false);

  // 회전 유무 판단
  const [isRotation, setIsRotation] = useState(false);

  // 회전 정보 (서버에 저장된 좌표로 수정하기)
  const [rotation, setRotation] = useState(0);

  // 타겟 정보
  const [target, setTarget] = useRecoilState(itemTargetState);

  const { scene, camera, gl } = useThree();
  const raycaster = new THREE.Raycaster();

  function intersect(pos: THREE.Vector2) {
    raycaster.setFromCamera(pos, camera);
    return raycaster.intersectObjects(scene.children);
  }

  // const dispatch = useAppDispatch();
  // const handlePositionUpdate = (
  //   id: number,
  //   x: string,
  //   y: string,
  //   z: string
  // ) => {
  //   dispatch(
  //     positionUpdate({
  //       diaryId: id,
  //       x: x,
  //       y: y,
  //       z: z,
  //     })
  //   );
  // };

  useEffect(() => {
    gl.domElement.addEventListener("click", () => {
      if (isDragging) {
        setIsDragging(false);
      }
    });

    // const handleWindowClick = (e: MouseEvent) => {
    //   if (isDragging) {
    //     setIsDragging(false);
    //   }
    // };
  }, [isDragging]);

  useFrame(({ mouse }) => {
    if (isDragging) {
      const found = intersect(mouse);

      if (found.length > 0) {
        for (let i = 0; i < found.length; i++) {
          if (!found[i].object.userData.ground) continue;

          // 물체가 마우스와 만난 지점으로 위치를 업데이트하기
          const newPosition = found[i].point;
          setPosition({ x: newPosition.x, y: -2.5, z: newPosition.z });
          break;
        }
      }
    }
  });

  // 물체 회전
  if (props.rotationButtonRef.current) {
    // console.log(target, 2);

    if (target === "chair") {
      props.rotationButtonRef.current.addEventListener("click", () => {
        // console.log("click", 2);
        setRotation((rotation + 10) % 360);
      });
    }
  }

  return (
    <>
      <group
        {...props}
        dispose={null}
        position={[position.x, position.y, position.z]}
        scale={0.8}
        userData={{ draggable: true, name: "chair" }}
        onClick={() => {
          if (!isDragging) setIsDragging(true);
          setTarget("chair");
        }}
        rotation={[0, THREE.MathUtils.degToRad(rotation), 0]}
      >
        <mesh
          geometry={nodes.Chair.geometry}
          material={materials.White}
          rotation={[0, 0.99, 0]}
          scale={0.86}
          userData={{ name: "chair" }}
        >
          <mesh
            geometry={nodes.Circle.geometry}
            material={materials.Wood2}
            position={[0.14, 0, 0]}
            userData={{ name: "chair" }}
          />
        </mesh>
      </group>
    </>
  );
}

// useGLTF.preload("/models/items/white_chair_1.glb");
