/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/cs_direct.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane009: THREE.Mesh;
    Plane010: THREE.Mesh;
    Text: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
    ["Material.012"]: THREE.MeshStandardMaterial;
    ["Material.013"]: THREE.MeshStandardMaterial;
  };
};

export function CSDirect(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/cs_direct.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane009.geometry}
        material={materials.Material}
        position={[0, 0, 0.03]}
      />
      <mesh
        geometry={nodes.Plane010.geometry}
        material={materials["Material.012"]}
        position={[0.17, 1.67, 0.09]}
        rotation={[-Math.PI, 0, -3.03]}
      />
      <mesh
        geometry={nodes.Text.geometry}
        material={materials["Material.013"]}
        position={[0.19, 1.56, 0.27]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.48}
      />
    </group>
  );
}
