/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/deco.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane020: THREE.Mesh;
    Plane021: THREE.Mesh;
    Plane036: THREE.Mesh;
  };
  materials: {
    ["Material.011"]: THREE.MeshStandardMaterial;
    ["Green.001"]: THREE.MeshStandardMaterial;
  };
};

export function Deco(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/deco.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane020.geometry}
        material={materials["Material.011"]}
        position={[2.4, 0, 3.02]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Plane021.geometry}
        material={materials["Material.011"]}
        position={[2.66, 0, 2.43]}
        scale={0.68}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Plane036.geometry}
        material={materials["Green.001"]}
        position={[3.21, 0.06, 3.27]}
        rotation={[-0.05, -0.33, -0.26]}
        scale={0.45}
        castShadow={true}
      />
    </group>
  );
}
