/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/feed.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh: THREE.Mesh;
    Mesh_1: THREE.Mesh;
    Mesh_2: THREE.Mesh;
    Mesh_3: THREE.Mesh;
    Mesh_4: THREE.Mesh;
    Mesh_5: THREE.Mesh;
    Mesh_6: THREE.Mesh;
    Mesh_7: THREE.Mesh;
    Mesh_8: THREE.Mesh;
    Mesh_9: THREE.Mesh;
    Video_Window: THREE.Mesh;
    Circle005: THREE.Mesh;
    Plane005: THREE.Mesh;
    Plane003: THREE.Mesh;
    Sidebar: THREE.Mesh;
    Plane008_1: THREE.Mesh;
    Plane008_2: THREE.Mesh;
    Plane008_3: THREE.Mesh;
  };
  materials: {
    ["Red.001"]: THREE.MeshStandardMaterial;
    ["White.001"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    White: THREE.MeshStandardMaterial;
    ["Dark.001"]: THREE.MeshStandardMaterial;
    bg: THREE.MeshStandardMaterial;
    Red: THREE.MeshStandardMaterial;
    Dark: THREE.MeshStandardMaterial;
  };
};

export function Feed(props: JSX.IntrinsicElements["group"] | any) {
  const { nodes, materials } = useGLTF("/models/feed.glb") as GLTFResult;
  return (
    <group ref={props.feedRef} {...props} dispose={null}>
      <group
        position={[-0.27, 0.99, 1.43]}
        rotation={[2.19, -0.96, 2.09]}
        scale={0.14}
      >
        <mesh geometry={nodes.Mesh.geometry} material={materials["Red.001"]} />
        <mesh
          geometry={nodes.Mesh_1.geometry}
          material={materials["White.001"]}
        />
      </group>
      <group
        position={[0.58, 1.7, -0.62]}
        rotation={[-2.98, -0.1, 2.99]}
        scale={0.1}
      >
        <mesh
          geometry={nodes.Mesh_2.geometry}
          material={materials["Red.001"]}
        />
        <mesh
          geometry={nodes.Mesh_3.geometry}
          material={materials["White.001"]}
        />
      </group>
      <group
        position={[0.63, 2.62, -0.73]}
        rotation={[-2.9, -0.34, -2.61]}
        scale={0.07}
      >
        <mesh
          geometry={nodes.Mesh_4.geometry}
          material={materials["Red.001"]}
        />
        <mesh
          geometry={nodes.Mesh_5.geometry}
          material={materials["White.001"]}
        />
      </group>
      <group
        position={[-0.54, 1.9, 0.13]}
        rotation={[2.43, -1.07, 2.63]}
        scale={0.1}
      >
        <mesh
          geometry={nodes.Mesh_6.geometry}
          material={materials["Red.001"]}
        />
        <mesh
          geometry={nodes.Mesh_7.geometry}
          material={materials["White.001"]}
        />
      </group>
      <group
        position={[1.62, 1.16, -0.41]}
        rotation={[2.71, 0.07, -2.63]}
        scale={0.1}
      >
        <mesh
          geometry={nodes.Mesh_8.geometry}
          material={materials["Red.001"]}
        />
        <mesh
          geometry={nodes.Mesh_9.geometry}
          material={materials["White.001"]}
        />
      </group>
      <mesh
        geometry={nodes.Video_Window.geometry}
        material={materials["default"]}
        position={[0.04, 1.79, -1.32]}
        scale={2.13}
      >
        <mesh
          geometry={nodes.Circle005.geometry}
          material={materials.White}
          position={[0.97, 0.58, 0.15]}
          scale={0.54}
        >
          <mesh
            geometry={nodes.Plane005.geometry}
            material={materials["Dark.001"]}
            position={[0, 0, 0.03]}
            rotation={[0, 0, -Math.PI / 4]}
          />
        </mesh>
        <mesh
          geometry={nodes.Plane003.geometry}
          material={materials.bg}
          position={[0, 0, 0.08]}
        />
      </mesh>
      <mesh
        geometry={nodes.Sidebar.geometry}
        material={materials.White}
        position={[-1.42, 1.4, 0.09]}
        scale={1.1}
      >
        <group position={[0.12, 0.6, 0.04]}>
          <mesh geometry={nodes.Plane008_1.geometry} material={materials.Red} />
          <mesh
            geometry={nodes.Plane008_2.geometry}
            material={materials.White}
          />
          <mesh
            geometry={nodes.Plane008_3.geometry}
            material={materials.Dark}
          />
        </group>
        <group position={[0.12, -0.05, 0.04]}>
          <mesh geometry={nodes.Plane008_1.geometry} material={materials.Red} />
          <mesh
            geometry={nodes.Plane008_2.geometry}
            material={materials.White}
          />
          <mesh
            geometry={nodes.Plane008_3.geometry}
            material={materials.Dark}
          />
        </group>
        <group position={[0.12, -0.71, 0.04]}>
          <mesh geometry={nodes.Plane008_1.geometry} material={materials.Red} />
          <mesh
            geometry={nodes.Plane008_2.geometry}
            material={materials.White}
          />
          <mesh
            geometry={nodes.Plane008_3.geometry}
            material={materials.Dark}
          />
        </group>
      </mesh>
    </group>
  );
}
