/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/floor.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh;
  };
  materials: {
    Green: THREE.MeshStandardMaterial;
  };
};

export function Floor(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/floor.glb") as GLTFResult;
  return (
    <group {...props} dispose={null} castShadow={true}>
      <mesh
        name="floor"
        geometry={nodes.Plane.geometry}
        material={materials.Green}
        castShadow={true}
        // receiveShadow={true}
      />
    </group>
  );
}
