/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/grass.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plant001: THREE.Mesh;
  };
  materials: {
    Green: THREE.MeshStandardMaterial;
  };
};

export function Grass(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/grass.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plant001.geometry}
        material={materials.Green}
        position={[-0.01, 0, 0.03]}
        scale={1.36}
      />
    </group>
  );
}

useGLTF.preload("/models/grass.glb");
