/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/ground.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
};

export function Ground(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group | any>();
  const { nodes, materials, animations } = useGLTF(
    "/models/ground.glb"
  ) as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" receiveShadow={true}>
        <mesh
          name="floor"
          geometry={nodes.Plane.geometry}
          material={materials["Material.001"]}
          receiveShadow={true}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/ground.glb");
