/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/house.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane001: THREE.Mesh;
    Plane001_1: THREE.Mesh;
    Roof: THREE.Mesh;
    Door_Frame: THREE.Mesh;
    Door: THREE.Mesh;
    Knob: THREE.Mesh;
    Window: THREE.Mesh;
    Plane006: THREE.Mesh;
    Chimney: THREE.Mesh;
    Shingle: THREE.Mesh;
    Shingle001: THREE.Mesh;
    Shingle002: THREE.Mesh;
    Shingle003: THREE.Mesh;
    Shingle004: THREE.Mesh;
    Shingle005: THREE.Mesh;
    Shingle006: THREE.Mesh;
    Brick001: THREE.Mesh;
    Brick002: THREE.Mesh;
    Brick003: THREE.Mesh;
    Brick004: THREE.Mesh;
    Brick005: THREE.Mesh;
    Brick006: THREE.Mesh;
    Brick007: THREE.Mesh;
    Brick: THREE.Mesh;
    Cylinder: THREE.Mesh;
    Vert: THREE.Mesh;
  };
  materials: {
    Wall: THREE.MeshStandardMaterial;
    Window: THREE.MeshStandardMaterial;
    Roof: THREE.MeshStandardMaterial;
    Wood: THREE.MeshStandardMaterial;
    Pink: THREE.MeshStandardMaterial;
    Yellow: THREE.MeshStandardMaterial;
    ["Roof.001"]: THREE.MeshStandardMaterial;
    ["Wall.001"]: THREE.MeshStandardMaterial;
    Grey: THREE.MeshStandardMaterial;
  };
};

export function House(props: JSX.IntrinsicElements["group"] | any) {
  const { nodes, materials } = useGLTF("/models/house.glb") as GLTFResult;
  return (
    <group
      ref={props.houseRef}
      {...props}
      dispose={null}
      scale={0.7}
      rotation={[0, -Math.PI / 2, 0]}
    >
      <group position={[-1.29, 0, 0.43]}>
        <mesh geometry={nodes.Plane001.geometry} material={materials.Wall} />
        <mesh
          geometry={nodes.Plane001_1.geometry}
          material={materials.Window}
          castShadow={true}
          receiveShadow={true}
        />
      </group>
      <mesh
        geometry={nodes.Roof.geometry}
        material={materials.Roof}
        position={[-1.29, 0, 0.43]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Door_Frame.geometry}
        material={materials.Wood}
        position={[-1.29, 0, 0.43]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Door.geometry}
        material={materials.Pink}
        position={[-1.29, 0, 0.43]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Knob.geometry}
        material={materials.Yellow}
        position={[0.56, 1.04, -1.28]}
        scale={0.09}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Window.geometry}
        material={materials.Wood}
        position={[-1.29, 0, 0.43]}
        castShadow={true}
      >
        <mesh
          geometry={nodes.Plane006.geometry}
          material={materials.Wood}
          castShadow={true}
        />
      </mesh>
      <mesh
        geometry={nodes.Chimney.geometry}
        material={materials.Wall}
        position={[-1.29, 0, 0.43]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Shingle.geometry}
        material={materials["Roof.001"]}
        position={[-0.23, 3.91, 2.45]}
        rotation={[0, 0, -0.6]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Shingle001.geometry}
        material={materials["Roof.001"]}
        position={[-0.24, 3.92, 1.63]}
        rotation={[0, 0, -0.6]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Shingle002.geometry}
        material={materials["Roof.001"]}
        position={[0.2, 3.62, 2.04]}
        rotation={[0, 0, -0.6]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Shingle003.geometry}
        material={materials["Roof.001"]}
        position={[0.18, 3.63, -0.43]}
        rotation={[0, 0, -0.6]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Shingle004.geometry}
        material={materials["Roof.001"]}
        position={[0.61, 3.34, -0.85]}
        rotation={[0, 0, -0.6]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Shingle005.geometry}
        material={materials["Roof.001"]}
        position={[-0.94, 4.39, -1.95]}
        rotation={[0, 0, -0.58]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Shingle006.geometry}
        material={materials["Roof.001"]}
        position={[-0.51, 4.1, -1.53]}
        rotation={[0, 0, -0.6]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Brick001.geometry}
        material={materials["Wall.001"]}
        position={[-0.69, 1.63, 3.6]}
        rotation={[Math.PI / 2, 0, 0]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Brick002.geometry}
        material={materials["Wall.001"]}
        position={[-0.99, 1.39, 3.6]}
        rotation={[Math.PI / 2, 0, 0]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Brick003.geometry}
        material={materials["Wall.001"]}
        position={[-1.51, 2.61, 3.6]}
        rotation={[Math.PI / 2, 0, 0]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Brick004.geometry}
        material={materials["Wall.001"]}
        position={[-1.3, 2.39, 3.6]}
        rotation={[Math.PI / 2, 0, 0]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Brick005.geometry}
        material={materials["Wall.001"]}
        position={[-1.76, 2.39, 3.36]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Brick006.geometry}
        material={materials["Wall.001"]}
        position={[-0.44, 0.2, 3.37]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Brick007.geometry}
        material={materials["Wall.001"]}
        position={[-0.93, 0.19, 3.6]}
        rotation={[Math.PI / 2, 0, 0]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Brick.geometry}
        material={materials["Wall.001"]}
        position={[-0.69, 0.43, 3.6]}
        rotation={[Math.PI / 2, 0, 0]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials.Grey}
        position={[-1.08, 4.49, 1.67]}
        scale={1.29}
        castShadow={true}
      >
        <mesh
          geometry={nodes.Vert.geometry}
          material={materials.Grey}
          position={[0, 0.24, 0]}
          castShadow={true}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/house.glb");
