/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/font/itemShop_font.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_9: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_25001: THREE.Mesh;
    Object_29: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_45001: THREE.Mesh;
    Object_46001: THREE.Mesh;
    Object_48: THREE.Mesh;
    Object_53: THREE.Mesh;
    Object_55: THREE.Mesh;
  };
  materials: {
    material_21: THREE.MeshStandardMaterial;
    material_15: THREE.MeshStandardMaterial;
    material_13: THREE.MeshStandardMaterial;
    material_6: THREE.MeshStandardMaterial;
    material_5: THREE.MeshStandardMaterial;
    material_3: THREE.MeshStandardMaterial;
    material_2: THREE.MeshStandardMaterial;
  };
};

export function ItemShopFont(props: JSX.IntrinsicElements["group"] | any) {
  const { nodes, materials } = useGLTF(
    "/models/font/itemShop_font.glb"
  ) as GLTFResult;

  return (
    <group
      ref={props.itemshopFontRef}
      dispose={null}
      scale={3}
      position={[1, -1, -10]}
    >
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials.material_21}
        position={[-0.27, 0.1, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Object_25.geometry}
        material={materials.material_15}
        position={[-1.41, 0.1, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Object_25001.geometry}
        material={materials.material_15}
        position={[-0.13, 0.11, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Object_29.geometry}
        material={materials.material_13}
        position={[0.32, 0.38, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Object_30.geometry}
        material={materials.material_13}
        position={[0.32, 0.38, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Object_45001.geometry}
        material={materials.material_6}
        position={[0.6, 0.38, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Object_46001.geometry}
        material={materials.material_6}
        position={[0.6, 0.38, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Object_48.geometry}
        material={materials.material_5}
        position={[0.59, 0.38, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Object_53.geometry}
        material={materials.material_3}
        position={[-0.57, 0.38, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        castShadow={true}
      />
      <mesh
        geometry={nodes.Object_55.geometry}
        material={materials.material_2}
        position={[-1.47, 0.38, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        castShadow={true}
      />
    </group>
  );
}

useGLTF.preload("/models/font/itemShop_font.glb");
