/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/bedside_light_1.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cylinder001_1: THREE.Mesh;
    Cylinder001_2: THREE.Mesh;
  };
  materials: {
    Beige: THREE.MeshStandardMaterial;
    White: THREE.MeshStandardMaterial;
  };
};

export function BedSide_light_1(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/items/bedside_light_1.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0, -2, 0]} scale={1} rotation={[0.2, 0.1, 0]}>
        <mesh
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Beige}
        />
        <mesh
          geometry={nodes.Cylinder001_2.geometry}
          material={materials.White}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/items/bedside_light_1.glb");
