/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/black_teatable_1.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Table001: THREE.Mesh;
    Plane013: THREE.Mesh;
    Plane014_1: THREE.Mesh;
    Plane014_2: THREE.Mesh;
    Plane014_3: THREE.Mesh;
    Plane014_4: THREE.Mesh;
    Plane014_5: THREE.Mesh;
    Plane014_6: THREE.Mesh;
  };
  materials: {
    Metal: THREE.MeshStandardMaterial;
    black: THREE.MeshStandardMaterial;
  };
};

export function Black_teatable_1(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/items/black_teatable_1.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Table001.geometry}
        material={materials.Metal}
        position={[-0.02, 0, -0.02]}
      >
        <mesh
          geometry={nodes.Plane013.geometry}
          material={materials.Metal}
          position={[0, 0.1, 0]}
        />
        <group position={[0, 1.59, 0]}>
          <mesh
            geometry={nodes.Plane014_1.geometry}
            material={materials.black}
          />
          <mesh
            geometry={nodes.Plane014_2.geometry}
            material={materials.black}
          />
        </group>
        <group position={[0, 1.59, 0]}>
          <mesh
            geometry={nodes.Plane014_3.geometry}
            material={materials.black}
          />
          <mesh
            geometry={nodes.Plane014_4.geometry}
            material={materials.black}
          />
        </group>
        <group position={[0, 1.59, 0]}>
          <mesh
            geometry={nodes.Plane014_5.geometry}
            material={materials.Metal}
          />
          <mesh
            geometry={nodes.Plane014_6.geometry}
            material={materials.Metal}
          />
        </group>
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/items/black_teatable_1.glb");
