/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/brown_table_1.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Table: THREE.Mesh;
    Plane020: THREE.Mesh;
    Plane042: THREE.Mesh;
  };
  materials: {
    Wood: THREE.MeshStandardMaterial;
    Metal: THREE.MeshStandardMaterial;
  };
};

export function Brown_table_1(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/items/brown_table_1.glb"
  ) as GLTFResult;
  return (
    <group
      {...props}
      dispose={null}
      scale={2}
      position={[0, -1.5, 0]}
      rotation={[0, THREE.MathUtils.degToRad(-90), 0]}
    >
      <directionalLight
        color={"#ffffff"}
        intensity={2}
        position={[2, 7, 3]}
        castShadow={true}
        shadow-camera-far={20}
        shadow-mapSize-width={2048}
        shadow-mapSize-height={2048}
        shadow-normalBias={0.05}
      />
      <mesh geometry={nodes.Table.geometry} material={materials.Wood}>
        <mesh geometry={nodes.Plane020.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Plane042.geometry} material={materials.Metal} />
      </mesh>
    </group>
  );
}

// useGLTF.preload("/models/items/brown_table_1.glb");
