/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/coffee_cup_1.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cup001: THREE.Mesh;
    Circle094: THREE.Mesh;
    Cup002: THREE.Mesh;
  };
  materials: {
    ["White.002"]: THREE.MeshStandardMaterial;
    ["Black.001"]: THREE.MeshStandardMaterial;
  };
};

export function Coffee_cup_1(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/items/coffee_cup_1.glb"
  ) as GLTFResult;
  return (
    <group
      {...props}
      dispose={null}
      scale={5}
      position={[0, -1.5, 0]}
      rotation={[0, THREE.MathUtils.degToRad(-90), 0]}
    >
      <directionalLight color={"#ffffff"} intensity={1} position={[2, 5, 3]} />
      <mesh geometry={nodes.Cup001.geometry} material={materials["White.002"]}>
        <mesh
          geometry={nodes.Circle094.geometry}
          material={materials["White.002"]}
        />
        <mesh
          geometry={nodes.Cup002.geometry}
          material={materials["Black.001"]}
        />
      </mesh>
    </group>
  );
}

// useGLTF.preload("/models/items/coffee_cup_1.glb");
