/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/elec_guitar_2.glb -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Stand003: THREE.Mesh
    Vert037: THREE.Mesh
    Circle036: THREE.Mesh
    Circle037: THREE.Mesh
    Circle038: THREE.Mesh
    Circle039: THREE.Mesh
    Circle040: THREE.Mesh
    Cylinder066: THREE.Mesh
    Cylinder067: THREE.Mesh
    Cylinder068: THREE.Mesh
    Cylinder069: THREE.Mesh
    Plane093: THREE.Mesh
    Plane094: THREE.Mesh
    Plane095: THREE.Mesh
    Plane096: THREE.Mesh
    Plane097: THREE.Mesh
    Vert038: THREE.Mesh
    Vert039: THREE.Mesh
  }
  materials: {
    Black: THREE.MeshStandardMaterial
    ['Black.002']: THREE.MeshStandardMaterial
    Chrome: THREE.MeshStandardMaterial
    Neck: THREE.MeshStandardMaterial
    Cream: THREE.MeshStandardMaterial
    ['Metal.001']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/elec_guitar_2.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Stand003.geometry} material={materials.Black} position={[-0.05, 1.49, 0.03]} rotation={[0, 0.37, 0]} scale={1.04}>
        <mesh geometry={nodes.Vert037.geometry} material={materials['Black.002']} position={[0.01, 1.15, 0]} rotation={[-Math.PI, 0, -1.8]} scale={1.12}>
          <mesh geometry={nodes.Circle036.geometry} material={materials.Chrome} position={[-0.58, 0.01, 0.16]} />
          <mesh geometry={nodes.Circle037.geometry} material={materials.Chrome} position={[-0.52, 0.01, 0.27]} />
          <mesh geometry={nodes.Circle038.geometry} material={materials.Chrome} position={[-0.71, 0.01, 0.15]} />
          <mesh geometry={nodes.Circle039.geometry} material={materials.Chrome} position={[-0.66, 0.01, 0.26]} />
          <mesh geometry={nodes.Circle040.geometry} material={materials.Chrome} position={[-0.04, 0.02, -0.16]} />
          <mesh geometry={nodes.Cylinder066.geometry} material={materials.Chrome} position={[-0.04, 0.02, -0.16]} />
          <mesh geometry={nodes.Cylinder067.geometry} material={materials.Chrome} position={[1.08, 0, -0.07]} />
          <mesh geometry={nodes.Cylinder068.geometry} material={materials.Chrome} position={[1.15, -0.01, -0.07]} />
          <mesh geometry={nodes.Cylinder069.geometry} material={materials.Chrome} position={[1.22, -0.01, -0.07]} />
          <mesh geometry={nodes.Plane093.geometry} material={materials.Neck} position={[0, 0.03, 0]} />
          <mesh geometry={nodes.Plane094.geometry} material={materials['Black.002']} position={[0.96, 0.03, 0]} rotation={[0, 0, -0.1]} />
          <mesh geometry={nodes.Plane095.geometry} material={materials.Chrome} position={[-0.14, 0.02, 0]} />
          <mesh geometry={nodes.Plane096.geometry} material={materials.Chrome} position={[-0.55, 0.02, 0]} />
          <mesh geometry={nodes.Plane097.geometry} material={materials.Chrome} position={[-0.46, 0.02, 0]} />
          <mesh geometry={nodes.Vert038.geometry} material={materials.Cream} position={[-0.27, 0.02, 0.13]} />
          <mesh geometry={nodes.Vert039.geometry} material={materials['Metal.001']} position={[-0.46, 0.04, -0.06]} />
        </mesh>
      </mesh>
    </group>
  )
}

useGLTF.preload('/elec_guitar_2.glb')
