/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/elec_guitar_1.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Stand002: THREE.Mesh;
    Vert032: THREE.Mesh;
    Circle031: THREE.Mesh;
    Circle032: THREE.Mesh;
    Circle033: THREE.Mesh;
    Circle034: THREE.Mesh;
    Circle035: THREE.Mesh;
    Cylinder059: THREE.Mesh;
    Cylinder060: THREE.Mesh;
    Cylinder061: THREE.Mesh;
    Cylinder062: THREE.Mesh;
    Plane087: THREE.Mesh;
    Plane088: THREE.Mesh;
    Plane089: THREE.Mesh;
    Plane090: THREE.Mesh;
    Vert034: THREE.Mesh;
  };
  materials: {
    Black: THREE.MeshStandardMaterial;
    ["Red.001"]: THREE.MeshStandardMaterial;
    Gold: THREE.MeshStandardMaterial;
    Chrome: THREE.MeshStandardMaterial;
    ["Black.002"]: THREE.MeshStandardMaterial;
    ["Metal.001"]: THREE.MeshStandardMaterial;
  };
};

export function Elec_guitar_1(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/items/elec_guitar_1.glb"
  ) as GLTFResult;
  return (
    <group
      {...props}
      dispose={null}
      scale={2.2}
      position={[0, -2.5, 0]}
      rotation={[0, THREE.MathUtils.degToRad(-90), 0]}
    >
      {/* <directionalLight
        color={"#FFFFFF"}
        intensity={0.2}
        position={[2, 5, 3]}
      /> */}
      <mesh geometry={nodes.Stand002.geometry} material={materials.Black}>
        <mesh
          geometry={nodes.Vert032.geometry}
          material={materials["Red.001"]}
          position={[0.01, 1.15, 0]}
          rotation={[-Math.PI, 0, -1.8]}
        >
          <mesh
            geometry={nodes.Circle031.geometry}
            material={materials.Gold}
            position={[-0.58, 0.01, 0.16]}
          />
          <mesh
            geometry={nodes.Circle032.geometry}
            material={materials.Gold}
            position={[-0.52, 0.01, 0.27]}
          />
          <mesh
            geometry={nodes.Circle033.geometry}
            material={materials.Gold}
            position={[-0.71, 0.01, 0.15]}
          />
          <mesh
            geometry={nodes.Circle034.geometry}
            material={materials.Gold}
            position={[-0.66, 0.01, 0.26]}
          />
          <mesh
            geometry={nodes.Circle035.geometry}
            material={materials.Gold}
            position={[-0.04, 0.02, -0.16]}
          />
          <mesh
            geometry={nodes.Cylinder059.geometry}
            material={materials.Chrome}
            position={[-0.04, 0.02, -0.16]}
          />
          <mesh
            geometry={nodes.Cylinder060.geometry}
            material={materials.Gold}
            position={[1.08, 0, -0.07]}
          />
          <mesh
            geometry={nodes.Cylinder061.geometry}
            material={materials.Gold}
            position={[1.15, -0.01, -0.07]}
          />
          <mesh
            geometry={nodes.Cylinder062.geometry}
            material={materials.Gold}
            position={[1.22, -0.01, -0.07]}
          />
          <mesh
            geometry={nodes.Plane087.geometry}
            material={materials["Black.002"]}
            position={[0.96, 0.03, 0]}
            rotation={[0, 0, -0.1]}
          />
          <mesh
            geometry={nodes.Plane088.geometry}
            material={materials.Gold}
            position={[-0.14, 0.02, 0]}
          />
          <mesh
            geometry={nodes.Plane089.geometry}
            material={materials.Gold}
            position={[-0.55, 0.02, 0]}
          />
          <mesh
            geometry={nodes.Plane090.geometry}
            material={materials.Gold}
            position={[-0.46, 0.02, 0]}
          />
          <mesh
            geometry={nodes.Vert034.geometry}
            material={materials["Metal.001"]}
            position={[-0.46, 0.04, -0.06]}
          />
        </mesh>
      </mesh>
    </group>
  );
}

// useGLTF.preload("/models/items/elec_guitar_1.glb");
