/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/leopard_chair_1.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Chair: THREE.Mesh;
    Plane043: THREE.Mesh;
  };
  materials: {
    Pattern: THREE.MeshStandardMaterial;
    Wood: THREE.MeshStandardMaterial;
  };
};

export function Leopard_chair_1(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/items/leopard_chair_1.glb"
  ) as GLTFResult;
  return (
    <group
      {...props}
      dispose={null}
      scale={2}
      position={[0, -2.5, 0]}
      rotation={[0, THREE.MathUtils.degToRad(-90), 0]}
    >
      <directionalLight color={"#FFFFFF"} intensity={1} position={[2, 5, 3]} />
      <mesh geometry={nodes.Chair.geometry} material={materials.Pattern}>
        <mesh geometry={nodes.Plane043.geometry} material={materials.Wood} />
      </mesh>
    </group>
  );
}

// useGLTF.preload("/models/items/leopard_chair_1.glb");
