/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/marble_table_2.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane009: THREE.Mesh;
    Circle008: THREE.Mesh;
    Plane010: THREE.Mesh;
    Plane011: THREE.Mesh;
  };
  materials: {
    Marble: THREE.MeshStandardMaterial;
    Metal: THREE.MeshStandardMaterial;
    White: THREE.MeshStandardMaterial;
    ["Black.001"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/items/marble_table_2.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane009.geometry}
        material={materials.Marble}
        position={[0.01, 0, 0.01]}
      >
        <mesh geometry={nodes.Circle008.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Plane010.geometry} material={materials.White} />
        <mesh
          geometry={nodes.Plane011.geometry}
          material={materials["Black.001"]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/items/marble_table_2.glb");
