/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/old_computer_1.glb -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane054: THREE.Mesh
    Plane054_1: THREE.Mesh
    Plane045: THREE.Mesh
    Plane056: THREE.Mesh
    Plane056_1: THREE.Mesh
    Plane056_2: THREE.Mesh
  }
  materials: {
    ['computer-beige']: THREE.MeshStandardMaterial
    ['screen-dos']: THREE.MeshStandardMaterial
    grey: THREE.MeshStandardMaterial
    black: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/old_computer_1.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-3.08, 1.82, -0.24]} rotation={[0, 0.11, 0]}>
        <mesh geometry={nodes.Plane054.geometry} material={materials['computer-beige']} />
        <mesh geometry={nodes.Plane054_1.geometry} material={materials['screen-dos']} />
        <mesh geometry={nodes.Plane045.geometry} material={materials.grey} position={[0.46, 0.22, 0.05]} rotation={[Math.PI / 2, 1.35, -Math.PI / 2]} scale={1.25} />
        <mesh geometry={nodes.Plane056.geometry} material={materials.black} />
        <mesh geometry={nodes.Plane056_1.geometry} material={materials['computer-beige']} />
        <mesh geometry={nodes.Plane056_2.geometry} material={materials.grey} />
      </group>
    </group>
  )
}

useGLTF.preload('/old_computer_1.glb')
