/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/photo_frame_1.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane015: THREE.Mesh;
    Plane015_1: THREE.Mesh;
  };
  materials: {
    Poster: THREE.MeshStandardMaterial;
    ["P1.001"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/items/photo_frame_1.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[-0.08, 2.95, -0.02]}>
        <mesh geometry={nodes.Plane015.geometry} material={materials.Poster} />
        <mesh
          geometry={nodes.Plane015_1.geometry}
          material={materials["P1.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/items/photo_frame_1.glb");
