/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/retro_arcadegame_1.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane050: THREE.Mesh;
    Plane050_1: THREE.Mesh;
    Plane050_2: THREE.Mesh;
    Plane050_3: THREE.Mesh;
    Plane050_4: THREE.Mesh;
    Plane031: THREE.Mesh;
    Cylinder_1: THREE.Mesh;
    Plane032: THREE.Mesh;
    Cylinder_2: THREE.Mesh;
    Plane033: THREE.Mesh;
  };
  materials: {
    black: THREE.MeshStandardMaterial;
    ["screen-arcade"]: THREE.MeshStandardMaterial;
    ["arcade-header"]: THREE.MeshStandardMaterial;
    ["led.001"]: THREE.MeshStandardMaterial;
    ["led.002"]: THREE.MeshStandardMaterial;
    grey: THREE.MeshStandardMaterial;
    ["black-gloss"]: THREE.MeshStandardMaterial;
    red: THREE.MeshStandardMaterial;
    led: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/items/retro_arcadegame_1.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0.03, 0, 0.02]} scale={1.13}>
        <mesh geometry={nodes.Plane050.geometry} material={materials.black} />
        <mesh
          geometry={nodes.Plane050_1.geometry}
          material={materials["screen-arcade"]}
        />
        <mesh
          geometry={nodes.Plane050_2.geometry}
          material={materials["arcade-header"]}
        />
        <mesh
          geometry={nodes.Plane050_3.geometry}
          material={materials["led.001"]}
        />
        <mesh
          geometry={nodes.Plane050_4.geometry}
          material={materials["led.002"]}
        />
        <mesh
          geometry={nodes.Plane031.geometry}
          material={materials.grey}
          position={[0.64, 1.92, 0.46]}
          rotation={[0, 0, -0.27]}
          scale={0.69}
        >
          <group position={[0, 0.08, 0]} scale={1.45}>
            <mesh
              geometry={nodes.Cylinder_1.geometry}
              material={materials["black-gloss"]}
            />
            <mesh
              geometry={nodes.Cylinder_2.geometry}
              material={materials.red}
            />
          </group>
        </mesh>
        <mesh
          geometry={nodes.Plane032.geometry}
          material={materials.grey}
          position={[0.64, 1.92, -0.3]}
          rotation={[0, 0, -0.27]}
          scale={0.69}
        >
          <group position={[0, 0.08, 0]} scale={1.45}>
            <mesh
              geometry={nodes.Cylinder_1.geometry}
              material={materials["black-gloss"]}
            />
            <mesh
              geometry={nodes.Cylinder_2.geometry}
              material={materials.red}
            />
          </group>
        </mesh>
        <mesh geometry={nodes.Plane033.geometry} material={materials.led} />
      </group>
    </group>
  );
}

// useGLTF.preload("/models/items/retro_arcadegame_1.glb");
