/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/white_chair_1.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Chair: THREE.Mesh;
    Circle: THREE.Mesh;
  };
  materials: {
    White: THREE.MeshStandardMaterial;
    Wood2: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/items/white_chair_1.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Chair.geometry}
        material={materials.White}
        rotation={[0, 0.99, 0]}
        scale={0.86}
      >
        <mesh
          geometry={nodes.Circle.geometry}
          material={materials.Wood2}
          position={[0.14, 0, 0]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/items/white_chair_1.glb");
