/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/wood_drawer_1.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Table: THREE.Mesh;
    Plane004: THREE.Mesh;
    Plane005: THREE.Mesh;
    Plane024: THREE.Mesh;
    Plane025: THREE.Mesh;
    Circle001: THREE.Mesh;
    Plane026_1: THREE.Mesh;
    Plane027: THREE.Mesh;
    Plane028: THREE.Mesh;
    Circle002: THREE.Mesh;
    Plane029: THREE.Mesh;
    Plane030: THREE.Mesh;
    Circle003: THREE.Mesh;
    Plane031: THREE.Mesh;
    Plane032: THREE.Mesh;
    Circle004: THREE.Mesh;
    Plane033: THREE.Mesh;
    Plane034: THREE.Mesh;
    Circle005: THREE.Mesh;
    Plane035: THREE.Mesh;
    Plane036: THREE.Mesh;
    Circle006: THREE.Mesh;
  };
  materials: {
    Wood: THREE.MeshStandardMaterial;
    Gold: THREE.MeshStandardMaterial;
  };
};

export function Wood_drawer_1(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/items/wood_drawer_1.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Table.geometry}
        material={materials.Wood}
        position={[-3.13, 0, 1.79]}
      >
        <mesh geometry={nodes.Plane004.geometry} material={materials.Wood} />
        <mesh
          geometry={nodes.Plane005.geometry}
          material={materials.Wood}
          position={[0, 2.09, 0]}
        />
        <mesh geometry={nodes.Plane024.geometry} material={materials.Wood}>
          <mesh
            geometry={nodes.Plane025.geometry}
            material={materials.Gold}
            position={[0.71, 1.78, 0.81]}
          >
            <mesh
              geometry={nodes.Circle001.geometry}
              material={materials.Gold}
              position={[0.01, 0, 0]}
            />
            <mesh
              geometry={nodes.Plane026_1.geometry}
              material={materials.Gold}
              position={[0.03, -0.01, 0]}
              rotation={[0, 0, -Math.PI / 2]}
            />
          </mesh>
          <mesh
            geometry={nodes.Plane027.geometry}
            material={materials.Gold}
            position={[0.71, 1.78, -0.81]}
          >
            <mesh
              geometry={nodes.Plane028.geometry}
              material={materials.Gold}
              position={[0.03, -0.01, 0]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.Circle002.geometry}
              material={materials.Gold}
              position={[0.01, 0, 0]}
            />
          </mesh>
          <mesh
            geometry={nodes.Plane029.geometry}
            material={materials.Gold}
            position={[0.71, 1.17, 0.81]}
          >
            <mesh
              geometry={nodes.Plane030.geometry}
              material={materials.Gold}
              position={[0.03, -0.01, 0]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.Circle003.geometry}
              material={materials.Gold}
              position={[0.01, 0, 0]}
            />
          </mesh>
          <mesh
            geometry={nodes.Plane031.geometry}
            material={materials.Gold}
            position={[0.71, 1.17, -0.81]}
          >
            <mesh
              geometry={nodes.Plane032.geometry}
              material={materials.Gold}
              position={[0.03, -0.01, 0]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.Circle004.geometry}
              material={materials.Gold}
              position={[0.01, 0, 0]}
            />
          </mesh>
          <mesh
            geometry={nodes.Plane033.geometry}
            material={materials.Gold}
            position={[0.71, 0.54, 0.81]}
          >
            <mesh
              geometry={nodes.Plane034.geometry}
              material={materials.Gold}
              position={[0.03, -0.01, 0]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.Circle005.geometry}
              material={materials.Gold}
              position={[0.01, 0, 0]}
            />
          </mesh>
          <mesh
            geometry={nodes.Plane035.geometry}
            material={materials.Gold}
            position={[0.71, 0.54, -0.81]}
          >
            <mesh
              geometry={nodes.Plane036.geometry}
              material={materials.Gold}
              position={[0.03, -0.01, 0]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.Circle006.geometry}
              material={materials.Gold}
              position={[0.01, 0, 0]}
            />
          </mesh>
        </mesh>
      </mesh>
    </group>
  );
}

// useGLTF.preload("/models/items/wood_drawer_1.glb");
