/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/wood_desk_0.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Desk: THREE.Mesh;
    Circle001: THREE.Mesh;
    Circle002: THREE.Mesh;
    Plane002: THREE.Mesh;
    Plane003: THREE.Mesh;
    Plane004: THREE.Mesh;
    Plane012: THREE.Mesh;
  };
  materials: {
    Wood2: THREE.MeshStandardMaterial;
    Wood: THREE.MeshStandardMaterial;
  };
};

export function Wood_desk_0(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/items/wood_desk_0.glb"
  ) as GLTFResult;
  return (
    <group
      {...props}
      dispose={null}
      position={[0, 0.7, 0]}
      rotation={[0, THREE.MathUtils.degToRad(-90), THREE.MathUtils.degToRad(7)]}
      scale={1.2}
    >
      <mesh
        geometry={nodes.Desk.geometry}
        material={materials.Wood2}
        position={[0, -2.16, 0]}
      >
        <mesh
          geometry={nodes.Circle001.geometry}
          material={materials.Wood2}
          position={[0.9, 1.3, 1.11]}
        />
        <mesh
          geometry={nodes.Circle002.geometry}
          material={materials.Wood2}
          position={[0.9, 0.7, 1.11]}
        />
        <mesh geometry={nodes.Plane002.geometry} material={materials.Wood2} />
        <mesh geometry={nodes.Plane003.geometry} material={materials.Wood2} />
        <mesh
          geometry={nodes.Plane004.geometry}
          material={materials.Wood2}
          position={[0, 0.33, 1.11]}
        />
        <mesh
          geometry={nodes.Plane012.geometry}
          material={materials.Wood}
          position={[0, 0.33, 1.11]}
        />
      </mesh>
    </group>
  );
}

// useGLTF.preload("/models/items/wood_desk_0.glb");
