/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/items/wood_table_1.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh: THREE.Mesh;
    Mesh_1: THREE.Mesh;
    Plane: THREE.Mesh;
  };
  materials: {
    ["Wood Dark"]: THREE.MeshStandardMaterial;
    Stump: THREE.MeshStandardMaterial;
    Steel: THREE.MeshStandardMaterial;
  };
};

export function Wood_table_1(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/items/wood_table_1.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0.01, 0, 0]}>
        <mesh
          geometry={nodes.Mesh.geometry}
          material={materials["Wood Dark"]}
        />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials.Stump} />
        <mesh geometry={nodes.Plane.geometry} material={materials.Steel} />
      </group>
    </group>
  );
}

// useGLTF.preload("/models/items/wood_table_1.glb");
